- modules/test/conn/python/src/connection_module.py
- modules/test/tls/python/src/tls_module.py
Fixes the following issues:
TLS Module:
- TLS client details reported results from the monitor when only startup had valid packets
Connection Module:
- Different devices reported DHCP Request options in different orders causing inconsistent results.
> Test fixes

- cmd/package
- framework/python/src/common/session.py
- framework/python/src/common/testreport.py
- framework/python/src/test_orc/test_orchestrator.py
- make/DEBIAN/control
- testing/api/test_api.py
Resolves the following bugs:
- Report URL is missing in report.json
- Total test count is double actual value
- Firmware version is not present in report or history table
- Test list and count is not reset when testing a second device
> Hotfix soft launch bugs

- modules/test/conn/python/src/connection_module.py
Updates the connection module to check the startup and monitor packet capture when determining whether a device has a SLAAC address.
> Check all packet captures for SLAAC address

- framework/python/src/common/session.py
A Testrun cannot be started if a device is created with an uppercase MAC address. This PR ignores case when searching for a device by MAC address.
> Fix device search issue

- framework/python/src/common/device.py
- framework/python/src/common/session.py
- framework/python/src/common/testreport.py
- framework/python/src/core/testrun.py
- framework/python/src/test_orc/test_orchestrator.py
- modules/test/base/python/src/test_module.py
- modules/test/baseline/conf/module_config.json
- modules/test/baseline/python/src/baseline_module.py
- modules/test/baseline/python/src/run.py
- modules/test/conn/python/src/connection_module.py
- modules/test/conn/python/src/dhcp_util.py
- modules/test/conn/python/src/run.py
- testing/device_configs/tester2/device_config.json
Now that the timezone has been set to the local timezone within test and network containers, the test code within the connection module does not function correctly - it is expecting the local time of the container to be UTC (the same as the time zone used in the DHCP server lease file). Therefore, wait times etc are not correct. This pull request manually converts local time back to UTC time when making date time comparisons with the DHCP lease expiration times.
> Resolve timezone issue in connection modules

- modules/test/conn/python/requirements.txt
- modules/test/conn/python/src/connection_module.py
- modules/test/conn/python/src/dhcp_util.py
Replaces https://github.com/google/testrun/pull/223
> Implement PR223 for clean merge into release

- modules/ui/src/app/components/general-settings/general-settings.component.ts
Ticket: 322476587
fix: change to set default selected value on close panel
https://screencast.googleplex.com/cast/NTM3OTcxNTkzMzE0MzA0MHw0ZTdiNzc5NC1lNQ
https://screencast.googleplex.com/cast/NTg1MTI5NjQ0NjgwODA2NHxlZDk2ZmJiNS0xYw
https://screenshot.googleplex.com/AWBzuewycuAMFwf.png
> 322476587: (fix) change to set default selected value on close panel

- modules/ui/src/app/store/effects.ts
Ticket: 323349282:
fix: [ui] change logic to hide message if only device port is saved
Link: https://screencast.googleplex.com/cast/NDU2ODc5ODk5NTY3NzE4NHw3MWRkMzA0Ni1iOA
> 323349282: (fix) [ui] change logic to hide message if only device port is saved

- modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.html
Ticket: 314934734
fix [ui] [a11y] repeated instructions  announced by screen reader - change accessible attributes 
Unit tests are all passed:
> 314934734: (fix) [ui] [a11y] repeated instructions  announced by screen reader

- modules/ui/package-lock.json
- modules/ui/package.json
Bumps [vite](https://github.com/vitejs/vite/tree/HEAD/packages/vite) to 4.5.2 and updates ancestor dependency [@angular-devkit/build-angular](https://github.com/angular/angular-cli). These dependencies need to be updated together.
Updates `vite` from 4.5.1 to 4.5.2
- [Release notes](https://github.com/vitejs/vite/releases)
- [Changelog](https://github.com/vitejs/vite/blob/v4.5.2/packages/vite/CHANGELOG.md)
- [Commits](https://github.com/vitejs/vite/commits/v4.5.2/packages/vite)
Updates `@angular-devkit/build-angular` from 16.2.11 to 16.2.12
- [Release notes](https://github.com/angular/angular-cli/releases)
- [Changelog](https://github.com/angular/angular-cli/blob/main/CHANGELOG.md)
- [Commits](https://github.com/angular/angular-cli/compare/16.2.11...16.2.12)
---
updated-dependencies:
- …
> Bump vite and @angular-devkit/build-angular in /modules/ui

- modules/ui/src/app/components/general-settings/general-settings.component.html
- modules/ui/src/app/components/general-settings/general-settings.component.spec.ts
- modules/ui/src/app/components/general-settings/general-settings.component.ts
> Enable save button when only one interface is available

- modules/ui/src/app/pages/settings/general-settings.component.spec.ts
- modules/ui/src/app/pages/settings/general-settings.component.ts
- modules/ui/src/app/pages/settings/settings.store.spec.ts
- modules/ui/src/app/pages/settings/settings.store.ts
Save button is disabled when port is no longer available
http://screencast/cast/NTA1NzYwMDAyOTcyMDU3NnwyYWE4MzZiNy04NA
Tests
> Save button is disabled when port is no longer available

- modules/ui/src/app/services/focus-manager.service.ts
- modules/ui/src/app/services/notification.service.spec.ts
- modules/ui/src/app/services/notification.service.ts
**Ticket:** 324061101 
**fix:** [a11y] GAR 1.3 the focus is not placed to the snackbar button
**tests**: update unit tests
Link: https://screencast.googleplex.com/cast/NjA4NDUyMTQ3NTcwMjc4NHwxZWZkOWFiNy1mNA
> 324061101: (fix) [a11y] GAR 1.3 the focus is not placed to the snackbar button

- modules/ui/src/styles.scss
**Ticket:** 324864346
**fix:** [a11Y] change color for field label to fix GAR 1.14 low color contrast
> 324864346: (fix) [a11Y] change color for field label to fix GAR 1.14 low color contrast

- modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.html
- modules/ui/src/app/components/version/version.component.ts
**Ticket:** 326951948
**fix:** [a11y] add accessible names for welcome modal and buttons
> 326951948: (fix) [a11y] add accessible names for welcome modal and buttons

- modules/ui/src/app/services/test-run.service.spec.ts
- modules/ui/src/app/services/test-run.service.ts
https://screencast.googleplex.com/cast/NDUyMjEzNTA2NTE5ODU5MnwxYWVmOGU4ZS02YQ
Tests
> Return old version if request fails

- modules/ui/src/app/pages/testrun/components/progress-table/progress-table.component.scss
- modules/ui/src/app/pages/testrun/progress.component.scss
**Ticket:** 325424134
**fix: [styles]** change borders for results table to be visible on scrolling
> 325424134: (fix) change borders for results table to be visible on scrolling

- framework/python/src/net_orc/network_orchestrator.py
- framework/python/src/net_orc/ovs_control.py
- framework/python/src/test_orc/test_orchestrator.py
Adds DHCP filters for OVS that are equivalent to DHCP snooping only allowing our virtual network DHCP servers.
ARP inspection flows have been disabled as they appear to break gRPC working between the DHCP servers even after removing them before connection module runs.  Still needs investigation into how we can fully enable this.
> Add arp dhcp inspection ovs

- modules/ui/src/app/app.component.ts
- modules/ui/src/app/pages/devices/device-repository.component.html
- modules/ui/src/app/store/state.ts
**Ticket:** 326193923
**fix:** change initial state value to prevent the callout for step 1 blinks on loading/reloading the page
https://screencast.googleplex.com/cast/NTg3OTM1NjY1OTMzNTE2OHw5MWMwNTA4Mi03YQ
https://screencast.googleplex.com/cast/NDkyODA3MTM5OTM3NDg0OHw1NGRkNDJmNC03MA
> 326193923: (fix) change to prevent the callout for step 1 blinks on loading/reloading the page

- modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.spec.ts
- modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.ts
- modules/ui/src/app/pages/testrun/progress.component.scss
**Ticket:** 327161779
**fix:** change get status with finished data to display a proper status on status bar
> 327161779: (fix) change get status with finished data to display a proper status on status bar

- modules/ui/src/app/mocks/progress.mock.ts
- modules/ui/src/app/pages/testrun/components/progress-table/progress-table.component.html
- modules/ui/src/app/pages/testrun/components/progress-table/progress-table.component.spec.ts
- modules/ui/src/app/pages/testrun/components/progress-table/progress-table.component.ts
Before
http://screencast/cast/NTUxODg2MTIzMDE0NTUzNnw4MzdjNjE5ZC05OQ
After
http://screencast/cast/NDk1MjU2ODc1MTk4MDU0NHxhNWFhZGZkOC0zMQ
> Save expand/collapse state

- modules/ui/src/app/app.component.html
- modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.html
- modules/ui/src/app/pages/settings/general-settings.component.html
**Ticket:** 328175839
**fix:** [a11Y] change to set focus on opening the settings panel
Link: https://screencast.googleplex.com/cast/NTM4MTE1MjY2NjgxMjQxNnw0MjQwZmU3Ni00Nw
> 328175839: (fix) [a11Y] change to set focus on opening the settings panel

- .github/workflows/testing.yml
Making the decision to remove test_tests due to the high failure rate. We will rework the automated testing of test modules soon.
> Disable test_tests temporarily

- modules/ui/src/app/mocks/progress.mock.ts
- modules/ui/src/app/pages/testrun/progress.component.spec.ts
- modules/ui/src/app/pages/testrun/progress.component.ts
> Cancelled status: empty table

- modules/ui/src/app/components/download-report-pdf/download-report-pdf.component.html
- modules/ui/src/app/components/download-report-pdf/download-report-pdf.component.spec.ts
- modules/ui/src/app/components/download-report-zip/download-report-zip.component.html
- modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts
- modules/ui/src/app/components/download-report/download-report.component.html
- modules/ui/src/app/components/download-report/download-report.component.spec.ts
- modules/ui/src/app/components/download-report/download-report.component.ts
- modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.html
- modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.ts
- modules/ui/src/app/pages/testrun/progress.component.spec.ts
**Ticket:** 329834205
**fix:** apply Angular tooltip to fix the long text issue on hover
Link: https://screencast.googleplex.com/cast/NTQwMTc3MjIwMDgyMDczNnwxZmM3OTgzNS1mMg
> 329834205: (fix) apply Angular tooltip to fix the long text issue on hover

- modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.html
- modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.scss
- modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.spec.ts
- modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.ts
**Ticket:** 328405692
**fix:** [a11y] [GAR 1.11, 1.13] add validation, error messages, hints for filters modal
> 328405692: (fix) [a11y] add validation, error messages, hints for filters modal

- modules/ui/src/styles.scss
**Ticket:** 330699330
**fix:** change styles to prevent unexpected space on pages with welcome modal
> 330699330: (fix) change styles to prevent unexpected space on pages with welcome modal

- modules/test/tls/python/src/tls_util.py
Allows all unencrypted traffic to private subnets initiated from the device.  Attempts to address https://github.com/google/testrun/issues/317
> Add private ip subnet filter for non-tls traffic

- modules/ui/src/app/pages/testrun/components/progress-initiate-form/progress-initiate-form.component.html
- modules/ui/src/app/pages/testrun/components/progress-initiate-form/progress-initiate-form.component.spec.ts
Ticket: 331572594: 
fix: [a11Y] GAR 1.13 The firmware field validation - add validation message to the UI
tests: add unit tests
> 331572594: (fix) [a11Y] GAR 1.13 The firmware field validation

- modules/test/tls/python/src/tls_util.py
Filter any SYN/ACK traffic during TLS client checks for unencrypted traffic.  These are used for both TLS and non-TLS but can't be used to determine which.  Also present in incomplete connections which could cause failures for connections to any external endpoint that is down or unexpected network issues.
> Add a SYN/ACK filter to unencrypted TLS check

- modules/ui/src/app/mocks/settings.mock.ts
- modules/ui/src/app/pages/settings/settings.store.spec.ts
- modules/ui/src/app/pages/settings/settings.store.ts
Ticket: 331378849
feat: add log level explanation text for connection settings
> 331378849: (feat) add log level explanation

- modules/ui/src/app/interceptors/error.interceptor.ts
- modules/ui/src/app/services/test-run.service.ts
+ extend timeout for next requests until stop
> Extend timeout when testrun is stopping

- modules/ui/src/app/app.component.html
- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/app.component.ts
- modules/ui/src/app/pages/settings/general-settings.component.html
- modules/ui/src/app/pages/settings/general-settings.component.scss
- modules/ui/src/app/pages/settings/general-settings.component.spec.ts
- modules/ui/src/app/pages/settings/general-settings.component.ts
- modules/ui/src/app/pages/testrun/progress.component.html
- modules/ui/src/app/pages/testrun/progress.component.spec.ts
- modules/ui/src/app/pages/testrun/progress.component.ts
- modules/ui/src/app/services/test-run.service.spec.ts
- modules/ui/src/app/services/test-run.service.ts
- modules/ui/src/styles.scss
Ticket: 331379891
feat: disable connection settings when testrun is in progress
> 331379891: (feat) disable connection settings when testrun is in progress

- modules/network/dhcp-1/python/src/grpc_server/dhcp_config.py
- modules/network/dhcp-1/python/src/grpc_server/dhcp_config_test.py
- modules/network/dhcp-1/python/src/grpc_server/network_service.py
- modules/network/dhcp-2/python/src/grpc_server/dhcp_config.py
- modules/network/dhcp-2/python/src/grpc_server/dhcp_config_test.py
- modules/network/dhcp-2/python/src/grpc_server/network_service.py
- modules/network/ntp/python/src/chronyd.py
- modules/network/ntp/python/src/ntp_server.py
- modules/test/base/python/src/test_module.py
- modules/test/conn/python/src/connection_module.py
- modules/test/dns/python/src/dns_module.py
- modules/test/tls/python/src/tls_module.py
- modules/test/tls/python/src/tls_util.py
- testing/pylint/test_pylint
- testing/tests/test_tests.py
- testing/unit/dns/dns_module_test.py
- testing/unit/nmap/nmap_module_test.py
- testing/unit/tls/tls_module_test.py
- Expand the pylint test to the entire project, not just framework
- Fix simple pylint issues
- Update pylint score
> Pylint score

- modules/ui/src/app/components/device-item/device-item.component.html
- modules/ui/src/app/components/device-item/device-item.component.scss
- modules/ui/src/app/components/device-item/device-item.component.spec.ts
- modules/ui/src/app/components/device-item/device-item.component.ts
- modules/ui/src/app/pages/devices/device-repository.component.html
- modules/ui/src/app/pages/devices/device-repository.component.spec.ts
- modules/ui/src/app/pages/devices/devices.store.spec.ts
- modules/ui/src/app/pages/devices/devices.store.ts
- modules/ui/src/app/services/test-run.service.spec.ts
- modules/ui/src/app/services/test-run.service.ts
- modules/ui/src/app/store/actions.ts
- modules/ui/src/app/store/effects.spec.ts
- modules/ui/src/app/store/effects.ts
- modules/ui/src/app/store/reducers.spec.ts
- modules/ui/src/app/store/reducers.ts
- modules/ui/src/app/store/selectors.spec.ts
- modules/ui/src/app/store/selectors.ts
- modules/ui/src/app/store/state.ts
http://screencast/cast/NTM2MzEyNTE3OTEyMTY2NHxkMzU4Mzg2ZS1iMw
> Disable device item if device in progress

- modules/ui/src/app/app.component.html
- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/app.component.ts
- modules/ui/src/app/app.module.ts
- modules/ui/src/app/components/shutdown-app-modal/shutdown-app-modal.component.html
- modules/ui/src/app/components/shutdown-app-modal/shutdown-app-modal.component.scss
- modules/ui/src/app/components/shutdown-app-modal/shutdown-app-modal.component.spec.ts
- modules/ui/src/app/components/shutdown-app-modal/shutdown-app-modal.component.ts
- modules/ui/src/app/components/shutdown-app/shutdown-app.component.html
- modules/ui/src/app/components/shutdown-app/shutdown-app.component.scss
- modules/ui/src/app/components/shutdown-app/shutdown-app.component.spec.ts
- modules/ui/src/app/components/shutdown-app/shutdown-app.component.ts
- modules/ui/src/app/providers/window.provider.ts
- modules/ui/src/app/services/test-run.service.spec.ts
- modules/ui/src/app/services/test-run.service.ts
- modules/ui/src/theming/colors.scss
Ticket: 333725552
feat: ability to shutdown Testrun
tests: add unit tests
Link: https://screencast.googleplex.com/cast/NDkwMDc3MjQ0NDYzNTEzNnxkOWU3NzdkOS1kOQ
> 333725552: (feat) ability to shutdown testrun

- modules/ui/src/app/pages/testrun/progress.component.spec.ts
- modules/ui/src/app/pages/testrun/progress.component.ts
IMPORTANT!
Before release remove event from google tag manager
> Adds ga to track testrun initiation

- modules/ui/src/app/pages/devices/components/device-form/device-form.component.html
- modules/ui/src/app/pages/devices/components/device-form/device-form.component.spec.ts
- modules/ui/src/app/pages/devices/components/device-form/device.validators.ts
- modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.ts
- modules/ui/src/app/pages/testrun/components/progress-initiate-form/progress-initiate-form.component.ts
> Change model and manufacturer length

- framework/python/src/common/session.py
- framework/python/src/test_orc/test_orchestrator.py
- local/system.json.example
Change default report limit behavior to keep all reports.  Setting max_device_reports property to default to zero keeps all reports.
Supersedes https://github.com/google/testrun/pull/409
> Change report limit default behavior

- modules/ui/src/app/app.component.html
- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/app.component.ts
- modules/ui/src/app/app.store.spec.ts
- modules/ui/src/app/app.store.ts
- modules/ui/src/app/mocks/certificate.mock.ts
- modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.html
- modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.spec.ts
- modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.ts
- modules/ui/src/app/pages/certificates/certificates.component.html
- modules/ui/src/app/pages/certificates/certificates.component.spec.ts
- modules/ui/src/app/pages/certificates/certificates.component.ts
- modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.spec.ts
- modules/ui/src/app/services/test-run.service.spec.ts
- modules/ui/src/app/services/test-run.service.ts
Video 
https://screencast.googleplex.com/cast/NjMxMTc4MzAxODAwNDQ4MHw0YjI5N2Y4OS0yYQ
Tests
> Adds delete certificate

- .gitignore
- framework/python/src/common/util.py
- modules/devices/faux-dev/python/src/util.py
- modules/test/base/python/src/util.py
- modules/test/tls/bin/check_cert_chain_signature.sh
- modules/test/tls/bin/check_cert_signature.sh
- modules/test/tls/bin/get_ciphers.sh
- modules/test/tls/bin/get_client_hello_packets.sh
- modules/test/tls/bin/get_handshake_complete.sh
- modules/test/tls/bin/get_non_tls_client_connections.sh
- modules/test/tls/bin/get_tls_client_connections.sh
- modules/test/tls/bin/get_tls_packets.sh
- modules/test/tls/python/src/tls_util.py
- testing/unit/tls/tls_module_test.py
I noticed that the TLS test will fail if the Root CA file placed in `local/root_certs` has a space in its name.
The filename parameters are not being properly handled when passed from `tls_utils.py` to `check_cert_signature.sh`, thus the openssl call in the bash script returns `No such file or directory`.
As the `get_started.md` file doesn't make any restriction to the file name, it can be misleading not supporting spaces: 
> NOTE: Place your local CA certificate in local/root_certs (any name with a .crt extension) to perform TLS server tests
In this PR, I basically added double quotes to parameters that can be a file.
I've also included logs to the response of the bash commands for easier debugging.
I only touched the TLS module, the same issue can still happen in other modules
> Support certificate names with spaces in TLS test

- modules/ui/src/app/components/download-report-pdf/download-report-pdf.component.html
- modules/ui/src/app/components/download-report-zip/download-report-zip.component.html
- modules/ui/src/app/components/download-report/download-report.component.html
- modules/ui/src/app/components/download-report/download-report.component.spec.ts
- modules/ui/src/app/components/download-report/download-report.component.ts
- modules/ui/src/app/mocks/progress.mock.ts
- modules/ui/src/app/pages/testrun/components/download-options/download-options.component.spec.ts
- modules/ui/src/app/pages/testrun/components/download-options/download-options.component.ts
+ adds event when download report is clicked on progress page
Tagmanager is updated
> Adds class for links to track report type on download

- modules/ui/src/app/mocks/progress.mock.ts
- modules/ui/src/app/mocks/reports.mock.ts
- modules/ui/src/app/model/testrun-status.ts
- modules/ui/src/app/pages/reports/history.component.ts
- modules/ui/src/app/pages/reports/reports.store.ts
http://screencast/cast/NTU5NDg4MTg0MDkwNjI0MHwyMDJmYjM2My02Yg
> For delete report take mac_addr from upper level

- modules/ui/src/app/app.component.html
- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/app.component.ts
- modules/ui/src/app/app.store.spec.ts
- modules/ui/src/app/app.store.ts
- modules/ui/src/app/mocks/certificate.mock.ts
- modules/ui/src/app/model/certificate.ts
- modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.html
- modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.scss
- modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.spec.ts
- modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.ts
- modules/ui/src/app/pages/certificates/certificate-upload-button/certificate-upload-button.component.html
- modules/ui/src/app/pages/certificates/certificate-upload-button/certificate-upload-button.component.scss
- modules/ui/src/app/pages/certificates/certificate-upload-button/certificate-upload-button.component.spec.ts
- modules/ui/src/app/pages/certificates/certificate-upload-button/certificate-upload-button.component.ts
- modules/ui/src/app/pages/certificates/certificates.component.html
- modules/ui/src/app/pages/certificates/certificates.component.scss
- modules/ui/src/app/pages/certificates/certificates.component.spec.ts
- modules/ui/src/app/pages/certificates/certificates.component.ts
- modules/ui/src/app/pages/certificates/certificates.store.spec.ts
- modules/ui/src/app/pages/certificates/certificates.store.ts
- modules/ui/src/app/services/notification.service.ts
- modules/ui/src/app/services/test-run.service.spec.ts
- modules/ui/src/app/services/test-run.service.ts
- modules/ui/src/styles.scss
http://screencast/cast/NDg1NDM2Nzk4MjE5MDU5MnwwMTA3ZTlhNS00Nw
> Adds upload certificate

- modules/ui/src/app/pages/certificates/certificates.store.ts
- modules/ui/src/app/pages/reports/reports.store.ts
- modules/ui/src/app/services/test-run.service.spec.ts
- modules/ui/src/app/services/test-run.service.ts
video after changes
http://screencast/cast/NDgwNDIxOTk2OTIwODMyMHw0ZTgyNTYxYy03ZQ
> Catch error on report/certificate deletion

- modules/ui/src/app/pages/certificates/certificates.component.html
- modules/ui/src/app/pages/certificates/certificates.component.spec.ts
- modules/ui/src/app/pages/certificates/certificates.component.ts
- modules/ui/src/app/pages/certificates/certificates.store.spec.ts
- modules/ui/src/app/pages/certificates/certificates.store.ts
video after changes
http://screencast/cast/NTUyODQyODczOTU1OTQyNHwzYzQwMDFkZi00Mg
> Adds focus on next or close button when certificate is deleted

- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/app.component.ts
- modules/ui/src/app/pages/settings/components/settings-dropdown/settings-dropdown.component.ts
- modules/ui/src/app/pages/settings/general-settings.component.ts
+ Do not remove form control on destroy as it causes error. No new control with the same name will be added on init 
https://github.com/angular/angular/blob/c1915f19c6f29b2421f1464e92e347d9bd86c07a/packages/forms/src/model/form_group.ts#L271
+ Call system/config on settings open
http://screencast/cast/NjYzOTYxNjUyOTUzMDg4MHw3ZDRkYjkwZS1lOA
Tests
> Reconnecting the adapters causes disabling the settings selection

- modules/ui/src/app/app-routing.module.ts
- modules/ui/src/app/app.component.html
- modules/ui/src/app/app.component.ts
- modules/ui/src/app/pages/devices/device-repository.component.scss
- modules/ui/src/app/pages/reports/history.component.scss
- modules/ui/src/app/pages/risk-assessment/risk-assessment-routing.module.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.scss
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.module.ts
- modules/ui/src/assets/icons/risk-assessment.svg
- modules/ui/src/styles.scss
Ticket: 339315842
feat: add risk assessment tab
> 339315842: (feat) add risk assessment tab

- modules/ui/src/app/mocks/profile.mock.ts
- modules/ui/src/app/model/profile.ts
- modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html
- modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss
- modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.scss
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.store.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
- modules/ui/src/app/services/test-run.service.spec.ts
- modules/ui/src/app/services/test-run.service.ts
Ticket: 339311887
feat: display saved risk profile
> 339311887: (feat) display saved risk profile

- modules/ui/src/styles.scss
It was broken when the scroll on mozilla was fixed. Styles changes, scroll is no appeared
> Fix style to allow screen reader to read label

- modules/ui/src/app/mocks/profile.mock.ts
- modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html
- modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.store.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
- modules/ui/src/app/services/test-run.service.spec.ts
- modules/ui/src/app/services/test-run.service.ts
Ticket: 339311250
feat: delete risk profile
tests: add unit tests
https://screencast.googleplex.com/cast/NTUwNzI4MzU0MTgxOTM5MnxlZDNmZjg0Ny05ZQ
https://screenshot.googleplex.com/vrgNJ5Ay6t4R2Jg
https://screenshot.googleplex.com/3b5N2KGtASLYWKj
> 339311250: (feat) delete risk profile

- modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.html
- modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html
- modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.spec.ts
Ticket: 341254121 
fix: [a11y] add item name for aria-labels delete and copy buttons
tests: add unit tests
https://screenshot.googleplex.com/GWx5RhZCNi54Cc6
https://screenshot.googleplex.com/ABKtLfKPiftRiMz
https://screenshot.googleplex.com/CxtCUToVChyM4cL
> 341254121: (fix) [a11y] add item name for aria-labels delete and copy buttons

- modules/ui/src/app/app.component.html
- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/app.component.ts
- modules/ui/src/app/app.module.ts
- modules/ui/src/app/app.store.spec.ts
- modules/ui/src/app/app.store.ts
- modules/ui/src/app/interceptors/loading.interceptor.ts
- modules/ui/src/app/pages/settings/general-settings.component.ts
- modules/ui/src/app/pages/testrun/progress.component.spec.ts
- modules/ui/src/app/pages/testrun/progress.component.ts
- modules/ui/src/app/pages/testrun/testrun.store.spec.ts
- modules/ui/src/app/pages/testrun/testrun.store.ts
- modules/ui/src/app/services/test-run.service.ts
- modules/ui/src/app/store/actions.ts
- modules/ui/src/app/store/effects.spec.ts
- modules/ui/src/app/store/effects.ts
- modules/ui/src/app/store/reducers.spec.ts
- modules/ui/src/app/store/reducers.ts
- modules/ui/src/app/store/selectors.spec.ts
- modules/ui/src/app/store/selectors.ts
- modules/ui/src/app/store/state.ts
http://screencast/cast/NDU2ODc5ODg1MzA3MDg0OHxjZDgxZDRmYy1iMQ
Tests
> Make testing statuses available outside of Testing Tab

- modules/ui/src/app/mocks/certificate.mock.ts
- modules/ui/src/app/model/certificate.ts
- modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.html
- modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.scss
- modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.spec.ts
- modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.ts
- modules/ui/src/app/pages/certificates/certificate-upload-button/certificate-upload-button.component.html
- modules/ui/src/app/pages/certificates/certificate-upload-button/certificate-upload-button.component.ts
- modules/ui/src/app/pages/certificates/certificate.validator.ts
- modules/ui/src/app/pages/certificates/certificates.component.spec.ts
- modules/ui/src/app/pages/certificates/certificates.component.ts
- modules/ui/src/app/pages/certificates/certificates.store.spec.ts
- modules/ui/src/app/pages/certificates/certificates.store.ts
Adds validation on file upload 
https://screencast.googleplex.com/cast/NjI5ODAxMzYyMTI4ODk2MHxjZjIzMzY3Ni1mMA
> Validate  CA certificate on FE

- modules/ui/src/app/mocks/certificate.mock.ts
- modules/ui/src/app/pages/certificates/certificate.validator.ts
Adds space in certificate name regexp
> The space is not allowed in the certificate name

- modules/ui/src/app/app.store.spec.ts
- modules/ui/src/app/pages/certificates/certificates.store.spec.ts
- modules/ui/src/app/pages/certificates/certificates.store.ts
- modules/ui/src/app/services/notification.service.spec.ts
- modules/ui/src/app/services/notification.service.ts
Adds class to fix focus flow
http://screencast/cast/NTA1NzMxNjA4MzcyODM4NHwyNDE2ODNmMS0wMA
> The focus is not moved to the snackbar with certificate validation rule

- modules/ui/src/app/pages/certificates/certificates.store.spec.ts
- modules/ui/src/app/pages/certificates/certificates.store.ts
- modules/ui/src/app/services/notification.service.ts
Focus first interactive element in cert container when cert snack bar closed
http://screencast/cast/NDkxNDg0MDU4NDg0NzM2MHxhZTdjODQ5ZS1mMw
> The focus goes to the main page element after adding the ceriticate

- modules/ui/src/app/app.store.spec.ts
- modules/ui/src/app/app.store.ts
> The snack bar with test attempt status appears  if the user is not on Testing page

- modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.html
- modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.scss
- modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.spec.ts
- modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.ts
> Update consent form

- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/app.component.ts
Adds announce when settings or certificate panel is opened
> The state of the system settings panel is not communicated in the screen reader

- framework/python/src/net_orc/network_orchestrator.py
Default docker network mode results in bad routing for internet traffic to/from the gateway module.  Bug originated from removal of private network during network module start which prevented default docker networking configuration. This sets network mode to none which allows only specific interface and routing setup by Testrun to be in control of traffic.
> Change network mode on network modules to fix gateway routing

- modules/ui/src/app/pages/devices/devices.component.spec.ts
- modules/ui/src/app/pages/devices/devices.component.ts
- modules/ui/src/app/pages/devices/devices.store.spec.ts
- modules/ui/src/app/pages/devices/devices.store.ts
- modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.html
- modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.spec.ts
- modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.ts
- modules/ui/src/app/pages/testrun/testrun.component.spec.ts
- modules/ui/src/app/pages/testrun/testrun.component.ts
- modules/ui/src/app/pages/testrun/testrun.store.spec.ts
- modules/ui/src/app/pages/testrun/testrun.store.ts
- modules/ui/src/app/services/test-run.service.spec.ts
- modules/ui/src/app/services/test-run.service.ts
Updates status with data from start response
http://screencast/cast/Njc0NDcwMzU3NDczNjg5NnwxNTczMGNhYi0yZg
> System status is not updated when test run is started

- modules/ui/src/app/app.component.html
- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.html
- modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.scss
- modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.spec.ts
- modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.ts
- modules/ui/src/app/components/version/version.component.ts
- modules/ui/src/app/model/version.ts
Ticket: 341966862
feat: display info about risk assessment in welcome modal
https://screencast.googleplex.com/cast/NjQ4ODA3NzA2NDIwODM4NHw2ZWE4OTk4MS1jMw
https://screenshot.googleplex.com/9DyMPCdUR6PXQbp
https://screenshot.googleplex.com/BMp3pX9xgYk3PnB
> 341966862: (feat) display info about risk assessment in welcome modal

- modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts
- modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html
- modules/ui/src/app/pages/reports/reports.component.html
- modules/ui/src/app/pages/reports/reports.component.scss
- modules/ui/src/app/pages/testrun/components/download-options/download-options.component.html
- modules/ui/src/app/pages/testrun/components/download-options/download-options.component.ts
Changes aria-label for Download Anyway button;
Fix keyboard navigation for Download zip component
Aria-label
Naviagation before
https://screencast.googleplex.com/cast/NjI4Nzg2ODM3MTY2NDg5Nnw0MzRkNTYxYS03NA
Navigation after
https://screencast.googleplex.com/cast/NjEwNjY4MDA3NjAwOTQ3MnxiM2NmMzgzYS04Zg
Focus on zip download modal
https://screencast.googleplex.com/cast/NTkwNjcyNTMyMzQwNzM2MHw1YTYzZjQyYS04Mw
> The Downlaod ZIP action can not be performed using the keaboard

- modules/ui/src/app/app.component.scss
- modules/ui/src/app/components/device-item/device-item.component.scss
- modules/ui/src/app/components/shutdown-app/shutdown-app.component.scss
- modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.scss
- modules/ui/src/app/pages/certificates/certificates.component.scss
- modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss
- modules/ui/src/app/pages/settings/settings.component.scss
- modules/ui/src/app/pages/testrun/components/download-options/download-options.component.scss
> Fix styles for helperbird

- modules/ui/src/app/mocks/profile.mock.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.scss
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts
- modules/ui/src/app/services/test-run.service.spec.ts
- modules/ui/src/app/services/test-run.service.ts
> Form from json validation

- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.scss
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
Enable draft button when profile name is present; enable save button when form is valid; remove discard button
http://screencast/cast/NjAyNDA2MjM1MzUzOTA3MnxkYjk0ZDM0Yi1hNw
Tests
> The action buttons are shown in the improper state

- modules/ui/src/app/mocks/profile.mock.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts
Fix validation - email allows , and ; as separator; change element for text-long - textarea; adds separate validation for max length
Tests
Screenshots after changes
> Field validation issues

- modules/ui/src/app/app.store.spec.ts
- modules/ui/src/app/app.store.ts
- modules/ui/src/app/mocks/profile.mock.ts
- modules/ui/src/app/model/profile.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.store.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
- modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.spec.ts
- modules/ui/src/app/services/test-run.service.spec.ts
- modules/ui/src/app/services/test-run.service.ts
- modules/ui/src/app/store/actions.ts
- modules/ui/src/app/store/effects.spec.ts
- modules/ui/src/app/store/effects.ts
http://screencast/cast/NjEzNjc0MDQxNzg5NjQ0OHxmOTZhOTNmOS1lZg
> Save new risk profile

- modules/ui/src/app/mocks/profile.mock.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
Tests
https://screencast.googleplex.com/cast/NjU0NzkwNDE0NjcwMjMzNnxlMDIyM2ViYi02OA
> Adds save draft

- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Tests
http://screencast/cast/NTY3NDM2MTgyMTMzMTQ1Nnw1NzJmOTlmNy0wNg
> Close form after selected risk profile was deleted

- framework/python/src/common/testreport.py
> Render informational result correctly

- modules/test/conn/python/src/connection_module.py
If no DHCPREQUEST detected from device, single IP test would report as multiple IP's detected. Accounts for this state and reports proper messaging.
> Fix bad multiple ip report when no ip requested

- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.store.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
- modules/ui/src/app/services/focus-manager.service.ts
Return focus on create button when new profile created; return focus on profile is profile was edited
https://screencast.googleplex.com/cast/NTk5ODEyOTU0MjMzMjQxNnw3MWY5ODE0NC1hYw
> The focus is not shown after the risk profile has been created

- modules/ui/src/app/mocks/profile.mock.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
Small refactoring; update validators on selected profile update and on profile list update
Tests
http://screencast/cast/NjU3MTEzMTI2MjczMDI0MHw3YWQ3NDBmOS0wYg
> The risk profile name of removed risk profile can not be used for another risk profile

- modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts
- modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts
- modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.spec.ts
- modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.ts
- modules/ui/src/app/mocks/profile.mock.ts
Show only valid profile in modal; fix condition to not download profile if redirect button clicked
Tests
http://screencast/cast/NTgxNjcwNDg1NTcwMzU1MnwxNjYwMmFmNy0wZA
> The risk profile draft is shown in the dropdown on the Download  ZIP popup; 404 error on redirect

- modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts
- modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts
- modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html
- modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.spec.ts
- modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.ts
- modules/ui/src/app/pages/reports/reports.component.html
- modules/ui/src/app/pages/reports/reports.component.spec.ts
- modules/ui/src/app/pages/reports/reports.store.spec.ts
- modules/ui/src/app/pages/reports/reports.store.ts
- modules/ui/src/app/pages/testrun/components/download-options/download-options.component.html
- modules/ui/src/app/pages/testrun/components/download-options/download-options.component.ts
- modules/ui/src/app/pages/testrun/testrun.component.html
- modules/ui/src/app/pages/testrun/testrun.component.spec.ts
- modules/ui/src/app/pages/testrun/testrun.store.spec.ts
- modules/ui/src/app/pages/testrun/testrun.store.ts
Tests
https://screencast.googleplex.com/cast/NDk2OTQ4NTUxMjQ3NDYyNHxmYTkwMjE4MC1iZQ
> Fix error when only draft profiles are exist

- modules/ui/src/app/app.store.spec.ts
- modules/ui/src/app/app.store.ts
- modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html
- modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss
- modules/ui/src/app/services/focus-manager.service.spec.ts
- modules/ui/src/app/services/focus-manager.service.ts
https://screencast.googleplex.com/cast/NTM1OTY2NTY3NTIzOTQyNHxjMzAyYzg0Yi03Zg
http://screencast/cast/NDUwODE3MTY2NTE0NTg1Nnw4NGU2M2JjNS1iOQ
> Focus fix; fix profile status icon

- framework/python/src/common/risk_profile.py
- framework/python/src/common/session.py
Example PDF output with long answers: 
[profile.pdf](https://github.com/user-attachments/files/16101298/profile.pdf)
JSON file is also formatted correctly.
> Support longer string answers in profile PDF

- framework/python/src/net_orc/network_orchestrator.py
When testing multiple devices within the same session, the runtime/test folder does not cleanup old devices, only the current one being tested on subsequent tests.  This causes multiple test reports from different devices to be stored incorrectly in the reports folder. PR cleans up all devices in the runtime/test folder on each new run.
> Cleanup old test devices from runtime

- modules/test/base/python/src/test_module.py
Remove the skipped result from the base test module. Skipped results should no longer exist and have now been replaced with Feature Not Detected or Error.
> Remove skipped result

- framework/python/src/api/api.py
- framework/python/src/common/session.py
Users should not be able to have duplicate devices in their device repository. This includes checking for a duplicate MAC address, or duplicate manufacturer and model combination. This pull requests adds an additional check to ensure a device with the same manufacturer and model does not already exist - returning error 409 if one is found.
> Prevent creating device with duplicate manufacturer and model

- framework/python/src/test_orc/test_orchestrator.py
Precondition: Run the test attempt till completion to get the report. Create 1 complete risk profile.
Open the Reports page
Click the button Download ZIP for the report generated in the precondition.
Select the risk profile and click Download
Open the Risk assessment page and remove the risk profile. The list should be empty
Open the Reports page and click the button Download ZIP again
Click Download anyway ( without risk profile)
Open the ZIP folder Actual result: the profile PDF is available inside the folder. Expected: the profile is not available.
> Remove profile from runtime once included in ZIP

- modules/ui/src/app/store/effects.spec.ts
- modules/ui/src/app/store/effects.ts
Do not show settings callout if there are no interfaces and saved settings
tests
screenshot after changes
> 2 callouts about system settings are shown on the first run

- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/app.component.ts
- modules/ui/src/app/app.store.spec.ts
- modules/ui/src/app/app.store.ts
- modules/ui/src/app/mocks/reports.mock.ts
- modules/ui/src/app/mocks/testrun.mock.ts
- modules/ui/src/app/model/testrun-status.ts
- modules/ui/src/app/pages/reports/reports-routing.module.ts
- modules/ui/src/app/pages/reports/reports.component.spec.ts
- modules/ui/src/app/pages/reports/reports.component.ts
- modules/ui/src/app/pages/reports/reports.module.ts
- modules/ui/src/app/pages/reports/reports.store.spec.ts
- modules/ui/src/app/pages/reports/reports.store.ts
- modules/ui/src/app/store/actions.ts
- modules/ui/src/app/store/effects.spec.ts
- modules/ui/src/app/store/effects.ts
- modules/ui/src/app/store/reducers.spec.ts
- modules/ui/src/app/store/reducers.ts
- modules/ui/src/app/store/selectors.spec.ts
- modules/ui/src/app/store/selectors.ts
- modules/ui/src/app/store/state.ts
Set testrun IDLE status if report of finished test run is removed
Reports moved to global store
http://screencast/cast/NjQxOTQ0NDc2MTg4NjcyMHw2YWI1NTFiMi0xNA
> The Download PDF button is enabled for the latest test run on the Testing page if the report was deleted on the Reports page

- modules/ui/src/app/pages/devices/devices.store.ts
- modules/ui/src/app/services/test-run.service.ts
Before
http://screencast/cast/NjQ5MTczNDQ5NzI5NjM4NHxhNDhhOWJmMS04OA
After
http://screencast/cast/NDUzNTM1OTcxNDA5OTIwMHw3YTc5NzI1OC1iMA
> Catch error to proceed with device creation/editing

- framework/python/src/common/util.py
Removes logging of output from the util class.  Even with debug option this spams the output.
> Remove output logging from OS level commands

- framework/python/src/net_orc/network_orchestrator.py
- framework/python/src/test_orc/test_orchestrator.py
Attaches the testrun.log file to the testing directory.
Fixes a bug where if you stop a Testrun during the monitor period, but start another Testrun immediately after, the Testrun is randomly cancelled. This is because the monitor period is still running in the background and detects the device interface being disconnected. This PR cancels the monitor sniffer when Testrun is cancelled.
> Add testrun.log to testing directory and fix bug with monitor

- modules/ui/src/app/app.component.html
- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/app.store.spec.ts
- modules/ui/src/app/app.store.ts
Ticket: 351338001
feat: update rule for the third step message and do not show the 3 step callout if reports are available
https://screencast.googleplex.com/cast/NjE2NDYwNTUyODE3ODY4OHw1NTM0NWYyMC02OA
> 351338001: (feat) update rule for the third step message

- modules/ui/src/app/mocks/profile.mock.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts
- modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Adds tooltip for copy and delete; show "same name" error when more than one copy is created
Tests
http://screencast/cast/NjE5MDE5NjM4NjE2ODgzMnxhNmU4OTMwMC1hNg
http://screencast/cast/NTUyMTcxMDI5NTAyMzYxNnwxNDc2MWJiNS1hOA
> The validation for duplicated name doesn't work for copied risk profile; The tooltips are not shown for action icons of the risk profile

- modules/ui/src/app/pages/certificates/certificates.store.spec.ts
- modules/ui/src/app/pages/certificates/certificates.store.ts
Ticket: 346999760
feat: [GA4]  add 'successful_saving_certificate' event for track CA Certificates
> 346999760: (feat) [GA4] Track CA Certificates

- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
> Change title for save profile dialog according to type of profile

- modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts
- modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts
Tests
Before - keyboard is ok, mouse is not
http://screencast/cast/NTY0NzE2NTA4MTc4MDIyNHxmMTEyYTI1NC1kNg
After - keyboard and mouse are ok
http://screencast/cast/NjM2MDMyMzA2MDY2MjI3Mnw5Mzk2MWVjZS00Zg
> Show tooltip only on keyboard or hover

- modules/ui/src/app/mocks/reports.mock.ts
- modules/ui/src/app/model/testrun-status.ts
- modules/ui/src/app/pages/reports/reports.component.spec.ts
- modules/ui/src/app/pages/reports/reports.component.ts
- modules/ui/src/app/pages/reports/reports.store.spec.ts
- modules/ui/src/app/pages/reports/reports.store.ts
Tests
https://screencast.googleplex.com/cast/NTY1OTk0MDUyOTExMTA0MHxhYTc1NGFkZi0zOQ
> Use device mac_addr if report mac_addr is missing

- framework/requirements.txt
- make/DEBIAN/control
When building testrun in the "wild", our computers hit PYPI directly, I'm assuming that Google is probably using a pypi cache internally so the behavior is different.  weasyprint pulls down the latest version of pydyf (0.11.0) which is incompatible with weasyprint 61.2 as specified in testrun's requirements.txt.  
Two possible paths for a fix:
- specify pydyf==0.8.0 in testrun's requirements.txt
- increment testrun's requirements.txt weasyprint requirement from 61.2 to 62.3
- I decided to move weasyprint to 62.3, and add pydyf to the requirements.txt and lock it to 0.11.0
- We have tested it internally and it resolves the runtime issues with testrun.
> Fix weasyprint/pydyf  dependency mismatch that causes an API runtime error (too many arguments passed to pydif function by weasyprint)

- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
> Adds close button for expired profile

- modules/ui/src/app/mocks/profile.mock.ts
- modules/ui/src/app/model/profile.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
- modules/ui/src/app/services/test-run.service.ts
Prevent opening of Expired risk profile
http://screencast/cast/NDY0ODE2MTcyODUyODM4NHw4ZTM2NmQwOS01Ng
> Revert "Expired profile (#619)"

- framework/python/src/net_orc/ip_control.py
- modules/ui/src/app/app.store.spec.ts
- modules/ui/src/app/app.store.ts
- modules/ui/src/app/components/wifi/wifi.component.html
- modules/ui/src/app/components/wifi/wifi.component.scss
- modules/ui/src/app/components/wifi/wifi.component.spec.ts
- modules/ui/src/app/components/wifi/wifi.component.ts
Tests
Screenshots after chages
> Change tooltip for internet icon

- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/app.component.ts
- modules/ui/src/app/app.store.spec.ts
- modules/ui/src/app/app.store.ts
- modules/ui/src/app/store/actions.ts
- modules/ui/src/app/store/effects.spec.ts
- modules/ui/src/app/store/effects.ts
- modules/ui/src/app/store/reducers.spec.ts
- modules/ui/src/app/store/reducers.ts
- modules/ui/src/app/store/selectors.spec.ts
- modules/ui/src/app/store/selectors.ts
- modules/ui/src/app/store/state.ts
Tests
Video
http://screencast/cast/NTA3MTg4NzI2MzU5NjU0NHxjMDE3NmQ5NC05Yw
> Update internet connection when device is In Progress, Monitoring, Waiting for Device status

- framework/python/src/api/api.py
- resources/devices/device_profile.json
- testing/api/test_api.py
I refactored the code so that a single endpoint will be used for all questions and answers. The questions are divided into steps, and if there is a subsequent step, a link to the next step will be included in the response. Each question and each answer has been assigned an ID. We discussed this solution with the team and concluded that it would be more convenient this way. Of course, at the moment, there is no need for such a structure, but it is implemented with the addition of new questions in mind.
> Endpoint for a device profile questions

- modules/ui/src/app/app.component.html
- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/components/callout/callout.component.html
- modules/ui/src/app/components/callout/callout.component.ts
- modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.html
- modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.scss
- modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.spec.ts
- modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.ts
- modules/ui/src/app/components/version/version.component.ts
- modules/ui/src/app/model/callout-type.ts
- modules/ui/src/app/model/version.ts
Ticket: 356882947
feat: add pilot program section to welcome modal
feat: remove risk profile section in welcome modal
https://screenshot.googleplex.com/9N3YQpu2YQdBwPr
https://screenshot.googleplex.com/8PDEE5pQM6tZTQc
> 356882947: (feat) add pilot program section to welcome modal

- modules/ui/src/app/app.component.html
- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/app.component.ts
- modules/ui/src/app/app.store.spec.ts
- modules/ui/src/app/app.store.ts
- modules/ui/src/app/components/callout/callout.component.html
- modules/ui/src/app/components/callout/callout.component.scss
- modules/ui/src/app/components/callout/callout.component.spec.ts
- modules/ui/src/app/components/callout/callout.component.ts
- modules/ui/src/app/components/device-item/device-item.component.spec.ts
- modules/ui/src/app/mocks/device.mock.ts
- modules/ui/src/app/mocks/reports.mock.ts
- modules/ui/src/app/mocks/testrun.mock.ts
- modules/ui/src/app/model/device.ts
- modules/ui/src/app/pages/devices/components/device-form/device-form.component.spec.ts
- modules/ui/src/app/pages/devices/components/device-form/device-form.component.ts
- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.spec.ts
- modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.spec.ts
- modules/ui/src/app/store/actions.ts
- modules/ui/src/app/store/effects.spec.ts
- modules/ui/src/app/store/effects.ts
- modules/ui/src/app/store/reducers.spec.ts
- modules/ui/src/app/store/reducers.ts
- modules/ui/src/app/store/selectors.spec.ts
- modules/ui/src/app/store/selectors.ts
- modules/ui/src/app/store/state.ts
- modules/ui/src/index.html
Adds expired device callout
Tests
http://screencast/cast/NDg2MTExMzcyMzI1NjgzMnw1N2FjMDAxMy1iZQ
> Display outdated device Banner

- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
Adds scroll
http://screencast/cast/NTk1NjgxODkzNjI2Njc1MnwwM2U2M2RmMC0wNg
http://screencast/cast/NTE1MTE0MzkwNTcyMjM2OHxiODRjYzcyMy1jZg
> Test modules are not visible when screen is magnified or in mobile view

- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
Adds padding to fit the errors
http://screencast/cast/NTAwNzE1MTE2NzcwMDk5MnxmMGNjZTM4ZS1mMg
> Overlapping of error messages in Device menu

- modules/ui/src/app/components/device-item/device-item.component.scss
- modules/ui/src/app/mocks/device.mock.ts
- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.spec.ts
- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
- modules/ui/src/app/pages/devices/devices.component.html
- modules/ui/src/app/pages/devices/devices.component.spec.ts
- modules/ui/src/app/pages/devices/devices.component.ts
- modules/ui/src/styles.scss
- modules/ui/src/theming/theme.scss
- modules/ui/src/theming/variables.scss
- Open Sans should be replaced with Google Sans
- When to Cancel closing on Step 3 or Step 4, user is navigated to Step 1 while should be returned to step where he clicked Close
- On Summary page there is no Text information about the next steps
- Also I noticed that when user clicks for the first time ‘Close’ button and Cancel closing, then clicks again for the second time Close button, Confirmation popup is not displayed anymore.
- One more issue is that when user deselects all test modules and clicks Go to next step button, no error message is displayed and only 'Test modules' text become red in color. I see expected result here is explicit error message
https://screencast.googleplex.com/cast/NjQ2Mjk2MzY1MjIzMTE2OHwxMDRmM2FiNC02ZA …
> Fix UI issues

- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
- modules/ui/src/app/pages/devices/devices.component.spec.ts
- modules/ui/src/app/pages/devices/devices.component.ts
Tests:
Screens after changes:
http://screencast/cast/NTQ4NTYzNDg4NDk5MzAyNHxmOWM3MjM3OC05Ng
> Adds delete device button

- modules/ui/src/app/model/device.ts
- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.spec.ts
- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
> Fix device testing type

- modules/ui/src/app/mocks/reports.mock.ts
- modules/ui/src/app/model/testrun-status.ts
- modules/ui/src/app/pages/reports/reports.component.html
- modules/ui/src/app/pages/reports/reports.store.spec.ts
- modules/ui/src/app/pages/reports/reports.store.ts
Ticket: 362724933
feat: add program type to results tab
https://screenshot.googleplex.com/57H7WxdGQUEcTiu
> 362724933: (feat) add program type to results tab

- modules/ui/src/app/components/stepper/stepper.component.scss
- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
- modules/ui/src/theming/variables.scss
Change style according to design
Before 
http://screencast/cast/NTI1NTA1MjQxODYxMzI0OHw1MWU4MGYxMy1jOQ
After
http://screencast/cast/NDg1MzE2ODkzOTcyODg5NnwxZDRlZDNmMi00Ng
> Fix design issues

- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
Change dialog height on resize
http://screencast/cast/NTY2MTY4NDA1MDk1MjE5MnxiNDJlZjAzOC0xZg
> Scroll is not displayed when to zoom the page with opened modal

- modules/ui/src/app/components/device-item/device-item.component.html
- modules/ui/src/app/components/device-item/device-item.component.ts
Ticket: 364828484
fix: [GAR 1.1] change program icon aria-label
https://screenshot.googleplex.com/BkjHNjrgG3WytdC
> 364828484: (fix) [GAR 1.1] change program icon aria-label

- modules/ui/src/app/components/device-item/device-item.component.html
- modules/ui/src/app/components/device-item/device-item.component.scss
- modules/ui/src/app/components/device-item/device-item.component.spec.ts
- modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.spec.ts
Ticket: 365059335
fix: [GAR 1.1] change device tile structure to allow read by Orca screen reader
https://screencast.googleplex.com/cast/NjIzMzcwNTQxMTUxMDI3MnxhMDJhZDU3OS0wOQ
> 365059335: (fix) [GAR 1.1] change device tile structure to allow read by Orca screen reader

- modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.html
- modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.ts
Fix text for High risk profile save window
Tests
> In High risk profile pop-up text is the same as in Limited risk

- modules/ui/src/app/pages/devices/devices.component.html
- modules/ui/src/app/pages/devices/devices.component.spec.ts
- modules/ui/src/app/pages/devices/devices.component.ts
Focus selected item on save
http://screencast/cast/NjU2NDcxNzE2NTI4MTI4MHxmYTA0NTg3Yy1lYg
> Focus disappears upon saving device profile in Edit modal

- modules/ui/src/app/app.component.html
- modules/ui/src/app/app.module.ts
- modules/ui/src/app/components/callout/callout.component.scss
- modules/ui/src/app/components/callout/dynamic-top.directive.ts
Adds dynamic top property to callouts
Before
After
> The callouts are merged visually if zooming in is 175% and more

- framework/python/src/api/api.py
- testing/api/test_api.py
Added the test for get 'system/testpacks' endpoint
Fixed the typing error in get_test_packs() from api.py
> Test for '/system/testpacks' 

- modules/ui/src/app/components/callout/dynamic-top.directive.ts
- modules/ui/src/styles.scss
Move bottom callouts to top when callout is destroyed; fix css selector
Before
http://screencast/cast/NjUyNjY4MjE0Mjg2NzQ1Nnw4OWRkM2I2NS0wNg
After
http://screencast/cast/NTcxMDk2MzE2MzUyOTIxNnwyZWM1NGZjYy1jZA
>   The callout/banner is shown improperly 

- modules/ui/src/app/mocks/testrun.mock.ts
- modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.spec.ts
- modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.ts
> Filter Not Started tests from test count

- modules/ui/src/app/components/download-report/download-report.component.html
- modules/ui/src/app/components/download-report/download-report.component.ts
- modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html
Ticket: 367673910
fix: prevent download PDF report button focused twice on completed testing modal
https://screencast.googleplex.com/cast/NjU2NzkwODc5NTc0NDI1NnwyODBjZGUzNS01ZQ
https://screencast.googleplex.com/cast/NTI4NjE2MjY0NTEyMzA3Mnw1NGJhNTc2YS03OQ
> 367673910: (fix) prevent download PDF report button focused twice on completed testing modal

- modules/ui/src/app/app.component.html
- modules/ui/src/app/app.component.ts
- modules/ui/src/app/components/callout/callout.component.html
Ticket: 366014294
feat: update callouts logic
https://screencast.googleplex.com/cast/NjA4MzI5MDk1OTE4Mzg3MnwzMTkzYWUyZi01Yg
https://screencast.googleplex.com/cast/NTMyOTYyOTU5MzIwNjc4NHw0ZjhhNTM2YS1lNg
> 366014294: (feat) update callouts logic

- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Do not show "Save changes" dialog when there is no changes in profile
Tests
http://screencast/cast/NjU4MzkwMDYzNjcwODg2NHwyOTE0NzgxNS1mYg
> The confirmation dialogto save changes  appears for the Risk profile without changes made. 

- testing/api/test_api.py
Added the test for "/devices/format" endpoint response code 200.
> Test for get devices format 

- modules/ui/src/app/services/notification.service.ts
Return focus on previous active element
http://screencast/cast/NDYyOTIzODEzNjE3NjY0MHxmYTYyNWIxNC03MA
> The focus is not returned to the previous element after closing the snackbar about new port availability

- modules/network/base/base.Dockerfile
- modules/network/radius/radius.Dockerfile
- testing/baseline/test_baseline
- testing/docker/ci_baseline/Dockerfile
- Updated the Ubuntu image for baseline Docker file 
- added --break-system-packages flag to bypass PEP668 for the new Ubuntu image.
- updated test_baseline to run tests inside venv
- updated test_baseline to clean the device network after running all the tests
> Fix baseline tests

- framework/python/src/common/session.py
- framework/python/src/common/testreport.py
- framework/python/src/test_orc/test_case.py
- framework/python/src/test_orc/test_orchestrator.py
Tests which are now informational (due to being run on a pilot device) will return 'optional_recommendations' instead of recommendations.
> Add optional recommendations for informational tests on pilot devices

- modules/ui/src/app/pages/devices/devices.component.spec.ts
- modules/ui/src/app/pages/devices/devices.component.ts
Ticket: 371177676
fix: set focus to the initial device if cancel on edit device
https://screencast.googleplex.com/cast/NDY2MTUxODA4Njk2MzIwMHwyYmRmNTBhMy1kZg
https://screencast.googleplex.com/cast/NjE1MjgzNTY5MDM5NzY5NnwyMGNhODNkNS1jZQ
> 371177676: (fix) set focus to the initial device if cancel on edit device

- modules/ui/src/app/app.store.ts
- modules/ui/src/app/mocks/settings.mock.ts
- modules/ui/src/app/pages/settings/components/settings-dropdown/settings-dropdown.component.scss
- modules/ui/src/app/pages/settings/settings.component.html
- modules/ui/src/app/pages/settings/settings.component.spec.ts
- modules/ui/src/app/pages/settings/settings.component.ts
- modules/ui/src/app/pages/settings/settings.store.spec.ts
- modules/ui/src/app/pages/settings/settings.store.ts
Ticket: 372768360
feat: [Settings] only device port is enabled in no internet mode
https://screenshot.googleplex.com/ABra7RNZmTnWD5j
https://screenshot.googleplex.com/5VYVZXZ4vsy8jSN
https://screencast.googleplex.com/cast/NTI4MDcwMDM4NjI0NjY1NnwyMTQ3YjUzZS05OA
https://screencast.googleplex.com/cast/NDkzNjkxOTg0NTY5OTU4NHwxYWY1OWExNC0zNQ
> 372768360: (feat) [Settings] only device port is enabled in no internet mode

- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Ticket: 374055268
fix: prevent overwrite copied profile
https://screencast.googleplex.com/cast/NjI1MTY3MjIzMjc4Nzk2OHxjNDY0OGNkYi0xYw
> 374055268: (fix) prevent overwrite copied profile

- resources/report/test_report_styles.css
Ticket: 374258745
fix: [PDF report] wrap long words into the next line to prevent cutting content
https://screenshot.googleplex.com/3KmSPmCwLkTtuNi
- in case of long words:
https://screenshot.googleplex.com/3MCRzQyuN2cy5A5
- base view:
https://screenshot.googleplex.com/3Y5wAwJWFBMpybX
> 374258745: (fix) [PDF report] wrap long words into the next line to prevent cutting content

- framework/python/src/api/api.py
- framework/python/src/core/session.py
Updated upload cert error handling:
-  if the organization name is missing
-  if the common name is missing
> Upload cert - error handling

- framework/requirements.txt
- testing/tests/test_tests
Updating to scapy from 2.5.0 to 2.6.0 removes the bellow warning:
/home/runner/work/testrun/testrun/venv/lib/python3.10/site-packages/scapy/layers/ipsec.py:512: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
cipher=algorithms.TripleDES,
/home/runner/work/testrun/testrun/venv/lib/python3.10/site-packages/scapy/layers/ipsec.py:516: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
cipher=algorithms.TripleDES,
> Scapy update to 2.6.0

- modules/test/base/base.Dockerfile
Added procps package in the base container. 
Before (module.log for all test modules) 
After (module.log for all test modules)
> Base container missing procps package

- modules/test/conn/python/src/connection_module.py
Added error handling if dhcp-1.pcap is empty.
Before
After
> Ipv6_slaac error handling

- modules/test/conn/bin/get_packet_counts.sh
- modules/test/conn/conf/module_config.json
- modules/test/conn/conn.Dockerfile
- modules/test/conn/python/src/connection_module.py
- testing/unit/conn/conn_module_test.py
Adds communication.network_type test as informational:
Result:
Packet counts are added as details json report, but not a part of current test module report:
```
{
"name": "communication.network.type",
"test_description": "How does the devie communicate (flow type) - Unicast, multicast broadcast?",
"expected_behavior": "Informational - One or more of these flow types are used",
"start": "2024-11-01T23:04:21.532194",
"result": "Informational",
"description": "Packet types detected: Multicast, Broadcast",
"details": {
"mac_address": "aa:bb:cc:dd:ee:ff",
"multicast": {
"from": 54,
"to": 0
},
"broadcast": {
"from": 18,
"to": 0
},
"unicast": {
"from": 0,
"to": 0
}
},
"end": "2024-11-01T23:04:29.586332",
"duration": "0:00:08.054138"
}
```
> Add communication network type test

- modules/ui/src/app/pages/testrun/testrun.component.html
- modules/ui/src/app/pages/testrun/testrun.component.scss
> The test attempt name is truncated without option to read the full text while zooming in

- modules/ui/src/app/services/test-run-mqtt.service.spec.ts
- modules/ui/src/app/services/test-run-mqtt.service.ts
- modules/ui/src/app/services/test-run.service.spec.ts
- modules/ui/src/app/services/test-run.service.ts
Ticket: 374289627
fix: change the report url from static to dynamic
https://screenshot.googleplex.com/3s9tUfoTdPt8L48
https://screenshot.googleplex.com/C9YEmM8ZcrD8QLc
> 374289627: (fix) change the report url from static to dynamic

- modules/test/tls/python/src/tls_module.py
Fixes error result for TLS server tests when no certificate can be validated.
Current results:
After fix:
> Fix tls error result

- modules/test/services/conf/module_config.json
- modules/test/services/python/src/services_module.py
Scans all TCP ports and adds an extra nmap test to cover the BACnet port scan. The intention is for the bacnet test to not actually run, as it is not included in any of the test packs. This is dependent on #956 but will work without it.
> Add BACnet test and extend port scan

- modules/test/conn/python/src/connection_module.py
Added error handling if GRPC server can't start due to port 5001 being blocked by UFW firewall.
BEFORE
Module.log
Report
AFTER
Module.log
Report
> Error handling for connection module

- framework/python/src/core/docker/test_docker_module.py
- framework/python/src/test_orc/test_orchestrator.py
- framework/python/src/test_orc/test_pack.py
- modules/test/base/python/src/test_module.py
- testing/unit/run_test_module.sh
This PR prevents tests from running if they are not present in the chosen test pack.
> Only run tests if they are included in the device's test pack

- modules/test/conn/python/src/connection_module.py
When connection.private_test is non compliant the default test_description is being recorded in the report
This is happening because final_result_details empty  string isn't updated when result['result'] is false
> connection.private_test

- modules/test/conn/python/src/connection_module.py
- modules/test/conn/python/src/dhcp_util.py
LOGGER.error(traceback.format_exc()) line from _run_subnet_test in the connection_module.py is causing the traceback errror message to be displayed in the connection module.log looking like is a traceback error that wasn't handled. This error was handled by exception block from _run_subnet_test and it happens when the lease is None 
Updated for this TypeError to be handled in dhcp_util.py
> Error handling when lease is None

- modules/test/protocol/python/src/protocol_bacnet.py
The bacnet traceback error is happening when validate_bacnet_source returns None.
> Bacnet traceback error

- modules/ui/src/app/pages/reports/components/filter-header/filter-header.component.html
- modules/ui/src/app/pages/reports/components/filter-header/filter-header.component.scss
- modules/ui/src/app/pages/reports/components/filter-header/filter-header.component.spec.ts
- modules/ui/src/app/pages/reports/components/filter-header/filter-header.component.ts
- modules/ui/src/app/pages/reports/reports.component.html
- modules/ui/src/app/pages/reports/reports.component.scss
- modules/ui/src/app/pages/reports/reports.component.spec.ts
- modules/ui/src/app/pages/reports/reports.component.ts
- modules/ui/src/app/pages/reports/reports.module.ts
- modules/ui/src/styles.scss
http://screencast/cast/NTkyMTE4MzQwODA2MjQ2NHw4MmFlNmU2Yy1jZQ
> Adds style for sorting; adds filter header component

- modules/ui/src/app/model/filters.ts
- modules/ui/src/app/pages/reports/components/filter-chips/filter-chips.component.html
- modules/ui/src/app/pages/reports/components/filter-chips/filter-chips.component.scss
- modules/ui/src/app/pages/reports/components/filter-chips/filter-chips.component.spec.ts
- modules/ui/src/app/pages/reports/components/filter-chips/filter-chips.component.ts
- modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.html
- modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.scss
- modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.spec.ts
- modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.ts
- modules/ui/src/app/pages/reports/components/filter-header/filter-header.component.html
- modules/ui/src/app/pages/reports/components/filter-header/filter-header.component.spec.ts
- modules/ui/src/app/pages/reports/components/filter-header/filter-header.component.ts
- modules/ui/src/app/pages/reports/reports.component.html
- modules/ui/src/app/pages/reports/reports.component.spec.ts
- modules/ui/src/app/pages/reports/reports.component.ts
- modules/ui/src/styles.scss
Ticket: 380254684
feat: apply gm3 for filtering report
https://screencast.googleplex.com/cast/NjQ2Njk5MTQ3NTkxNjgwMHwxZGE4MGMxMy04Mw
> 380254684: (feat) apply gm3 for filtering report

- README.md
- cmd/build_ui
- cmd/package
- docs/get_started.md
- modules/test/tls/bin/get_client_hello_packets.sh
- modules/test/tls/bin/get_non_tls_client_connections.sh
- modules/test/tls/bin/get_tls_client_connections.sh
- modules/test/tls/bin/get_tls_packets.sh
- modules/test/tls/python/src/tls_module.py
- modules/test/tls/python/src/tls_util.py
- testing/unit/tls/tls_module_test.py
In this PR:
- All TLS client scripts now use the source ethernet address instead of the ip address
- Added an error message if there is a space in the file path when running cmd/package
- Removed the requirement for usb ethernet adapter in the docs
- Checks that the user is in the docker group when running cmd/package
> Switch src ip to src mac for TLS client testing

- modules/ui/src/app/app.component.html
- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/app.component.ts
- modules/ui/src/app/pages/general-settings/components/settings-dropdown/settings-dropdown.component.html
- modules/ui/src/app/pages/general-settings/components/settings-dropdown/settings-dropdown.component.scss
- modules/ui/src/app/pages/general-settings/general-settings.component.html
- modules/ui/src/app/pages/general-settings/general-settings.component.scss
- modules/ui/src/app/pages/general-settings/general-settings.component.spec.ts
- modules/ui/src/app/pages/general-settings/general-settings.component.ts
- modules/ui/src/styles.scss
- modules/ui/src/theming/colors.scss
Ticket: 382095919: 
feat: add general settings page
https://screenshot.googleplex.com/4GhtH79v2q2TTcv
> 382095919: (feat) add general settings page

- modules/ui/src/app/app.component.html
- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/components/callout/callout.component.html
- modules/ui/src/app/components/callout/callout.component.scss
- modules/ui/src/app/components/callout/callout.component.spec.ts
- modules/ui/src/app/components/callout/callout.component.ts
- modules/ui/src/theming/colors.scss
- modules/ui/src/theming/variables.scss
Adds style for callouts; update component with signals; adds action in callout
> New callouts

- modules/ui/src/app/components/simple-dialog/simple-dialog.component.html
- modules/ui/src/app/components/simple-dialog/simple-dialog.component.scss
- modules/ui/src/app/pages/certificates/certificates.component.spec.ts
- modules/ui/src/app/pages/certificates/certificates.component.ts
- modules/ui/src/app/pages/certificates/components/certificates-table/certificates-table.component.scss
> Change style for delete certificate dialog

- modules/test/dns/resources/report_template.jinja2
- resources/report/test_report_styles.css
Ticket: 382100926
feat: change styles for dns module table
> 382100926: (feat) change styles for dns module table

- modules/ui/src/app/components/empty-message/empty-message.component.html
- modules/ui/src/app/components/empty-message/empty-message.component.scss
- modules/ui/src/app/components/empty-message/empty-message.component.spec.ts
- modules/ui/src/app/components/empty-message/empty-message.component.ts
- modules/ui/src/app/components/empty-page/empty-page.component.html
- modules/ui/src/app/components/empty-page/empty-page.component.spec.ts
- modules/ui/src/app/components/empty-page/empty-page.component.ts
- modules/ui/src/app/components/list-layout/list-layout.component.html
- modules/ui/src/app/components/list-layout/list-layout.component.scss
- modules/ui/src/app/components/list-layout/list-layout.component.spec.ts
- modules/ui/src/app/components/list-layout/list-layout.component.ts
- modules/ui/src/app/pages/devices/devices.component.html
- modules/ui/src/app/pages/devices/devices.component.scss
- modules/ui/src/app/pages/devices/devices.component.spec.ts
- modules/ui/src/app/pages/devices/devices.component.ts
- modules/ui/src/assets/icons/empty-devices.svg
> Change empty state for Devices page

- modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.html
- modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.scss
- modules/ui/src/styles.scss
Ticket: 382109519
feat: apply gm3 for welcome modal
https://screenshot.googleplex.com/89dP6RmscBUz7wy
> 382109519: (feat) apply gm3 for welcome modal

- modules/ui/src/app/pages/certificates/components/certificates-table/certificates-table.component.html
- modules/ui/src/app/pages/certificates/components/certificates-table/certificates-table.component.scss
- modules/ui/src/app/pages/certificates/components/certificates-table/certificates-table.component.ts
Ticket: 385715473
feat: add TLS callout to certificates tab
https://screenshot.googleplex.com/3oP5wkgJHbV22Xo
> 385715473: (feat) add TLS callout to certificates tab

- modules/ui/src/app/app.component.ts
- modules/ui/src/app/app.store.spec.ts
- modules/ui/src/app/app.store.ts
- modules/ui/src/app/components/device-item/device-item.component.scss
- modules/ui/src/app/pages/general-settings/general-settings.store.spec.ts
- modules/ui/src/app/pages/general-settings/general-settings.store.ts
- modules/ui/src/app/store/actions.ts
- modules/ui/src/app/store/effects.spec.ts
- modules/ui/src/app/store/effects.ts
Request settings when app is opened
> Warning callout for missing ports is displayed only on Settings tabs; Incorrect location for Steps callouts

- modules/ui/src/app/components/callout/callout.component.html
- modules/ui/src/app/components/callout/callout.component.scss
- modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.scss
- modules/ui/src/app/model/callout-type.ts
- modules/ui/src/app/pages/general-settings/general-settings.component.html
- modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.html
Change border color for warning callout; change icon for error callouts
before
after
> [GM3] The icon for warning callouts differs from the icons of other callouts

- modules/ui/src/app/pages/certificates/certificates.component.scss
- modules/ui/src/app/pages/certificates/components/certificates-table/certificates-table.component.scss
- modules/ui/src/styles.scss
- modules/ui/src/theming/variables.scss
Ticket: 387242169
fix: change availability of certificate page
https://screencast.googleplex.com/cast/NTU4MjA2NTY3NTI3MjE5MnxmYzYyNGI0OC1lZA
> 387242169: (fix) change availability of certificate page

- framework/python/src/core/testrun.py
If users enter the incorrect device mac address, debug message will be displayed on terminal during the test with device mac address found but ignored and the expected device mac address.
> Added debug message in case users enters an incorrect device mac address

- framework/python/src/common/testreport.py
- framework/python/src/test_orc/test_orchestrator.py
When zip file is exported, if the device profile has been changed the report will be updated with new device profile data
> Re-render device profile

- framework/python/src/core/session.py
- testing/api/profiles/invalid_name.json
- testing/api/test_api.py
When profile name contains '/' character it causes a crash.
Added an error message if the profile name contains any of the following characters: \<>?/:;@''][=^!
Added 2 tests for create and update profile when profile name is invalid. 
Moved the special characters check into session/validate_profile_json
> Handling error if profile name contains special characters

- modules/ui/src/app/components/list-layout/list-layout.component.html
- modules/ui/src/app/components/list-layout/list-layout.component.scss
- modules/ui/src/app/components/list-layout/list-layout.component.ts
- modules/ui/src/app/pages/devices/components/device-form/device.validators.ts
- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
- modules/ui/src/app/pages/devices/devices.component.html
- modules/ui/src/app/pages/devices/devices.component.ts
Ticket: 385169773
feat: add devices input form
https://screencast.googleplex.com/cast/NDkwMTgxNjk0Mzc3MTY0OHxjZGJhYjMyOC05OA
> 385169773: (feat) add devices input form

- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts
Ticket: 389661817
feat: change profile name validation. Not allowed symbols: <>?/:;@'"][=^!\#$%&*+{}|()
https://screencast.googleplex.com/cast/NTgzMjc2NDcyODI3OTA0MHwxMDU4NmIxOS04Nw
https://screencast.googleplex.com/cast/NjQwNzIwMTk0MDgzMjI1NnxhMTVlNDdlMi1lOQ
> 389661817: (feat) change profile name validation

- modules/ui/src/app/mocks/testrun.mock.ts
- modules/ui/src/app/model/testrun-status.ts
- modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.html
- modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.spec.ts
- modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.ts
- modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.html
- modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.scss
- modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.spec.ts
- modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.ts
Add column; change pilot text; change order of columns
> Rename Pilot test results

- modules/ui/src/app/components/device-tests/device-tests.component.spec.ts
- modules/ui/src/app/components/device-tests/device-tests.component.ts
- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
http://screencast/cast/NjcyMzYwMjQxNzE4ODg2NHwxMGFkMThhZC05NA
> Reset form values for new device

- modules/test/tls/python/src/tls_module.py
- modules/test/tls/resources/report_template.jinja2
- modules/test/tls/tls.Dockerfile
- resources/report/module_report_base.jinja2
- testing/unit/dns/reports/dns_report_local.html
- testing/unit/dns/reports/dns_report_local_no_dns.html
- testing/unit/ntp/reports/ntp_report_local.html
- testing/unit/ntp/reports/ntp_report_local_no_ntp.html
- testing/unit/services/reports/services_report_all_closed_local.html
- testing/unit/services/reports/services_report_local.html
- testing/unit/tls/reports/tls_report_ext_local.html
- testing/unit/tls/reports/tls_report_local.html
- testing/unit/tls/reports/tls_report_no_cert_local.html
- testing/unit/tls/reports/tls_report_single.html
report examples
[report.pdf](https://github.com/user-attachments/files/18423379/report.pdf)
rename html.pdf to html
[report.html.pdf](https://github.com/user-attachments/files/18423384/report.html.pdf)
> Jinja TLS report

- modules/ui/src/app/mocks/testrun.mock.ts
- modules/ui/src/app/model/testrun-status.ts
- modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.ts
- modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.ts
- modules/ui/src/app/pages/testrun/testrun.store.spec.ts
- modules/ui/src/app/pages/testrun/testrun.store.ts
- modules/ui/src/app/services/test-run.service.spec.ts
- modules/ui/src/app/services/test-run.service.ts
Ticket: 389657377
feat: add status Starting to UI
https://screenshot.googleplex.com/5unCJjAxhLvx97o
> 389657377: (feat) add status Starting to UI

- modules/ui/src/app/components/device-item/device-item.component.html
- modules/ui/src/app/components/device-item/device-item.component.scss
- modules/ui/src/app/components/device-item/device-item.component.spec.ts
- modules/ui/src/app/components/device-tests/device-tests.component.scss
- modules/ui/src/app/components/program-type-icon/program-type-icon.component.ts
- modules/ui/src/app/pages/devices/devices.component.html
- modules/ui/src/app/pages/devices/devices.component.scss
- modules/ui/src/theming/mixins.scss
>  3 dots menu should be disabled for devices under test

- modules/ui/src/app/components/callout/callout.component.scss
- modules/ui/src/app/pages/settings/settings.component.ts
Ticket: 388235982
fixes: 
- apply change for highlight necessary tab when navigate from callout 
- change styles for fix callout action button view on smaller page width
- for callout
https://screencast.googleplex.com/cast/NTkzNjM1MzAzMTIyNTM0NHxmZTEzNjEzMi02OA
- for setting tabs
https://screencast.googleplex.com/cast/NTU5NjM1NjEwNTIwNzgwOHwzNjg2NzAyYy1mOQ
- for callout
https://screencast.googleplex.com/cast/NjYxMTE0MjM1NTk3NjE5MnwyMjI5OWNhZC0xZQ
- for setting tabs
https://screencast.googleplex.com/cast/NDY3NTM2Mjk0NzU5NjI4OHwzZGJjNzY3Ny1kYw
> 388235982: (fix) setting and callout fixes

- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
- modules/ui/src/app/pages/devices/devices.component.html
- modules/ui/src/app/pages/devices/devices.component.ts
Show Discard dialog when changing the tab; show Discard dialog when clicking the Create new device
http://screencast/cast/NTIwNjMyNDI1MzAzMjQ0OHw5M2ZmMWYyYi02OA
> No warning popup appeared upon clicking on the ´ Create New Device ´ button and on another page when  editing the device

- resources/test_packs/pilot.json
- resources/test_packs/qualification.json
Port 47808 was not scanned. Added protocol.services.bacnet  in test_packs. 
Before
After
> Fix protocol.services.bacnet 

- resources/test_packs/pilot.json
Ticket: 392112885
feat: [2.1.1 release] rename results modals for Pilot - the descriptions for Completed modal with Pilot statuses "Proceed" and "Do Not Proceed" are changed
https://screenshot.googleplex.com/5Kr79y9p72CE4zz
https://screenshot.googleplex.com/xNvWY8nA5yXkRrz
https://screenshot.googleplex.com/6XXVEs3eJt9eDCr
https://screenshot.googleplex.com/59AuPtLisdDCPsd
> 392112885: (feat) [2.1.1 release] rename results modals for Pilot

- modules/ui/src/app/components/dynamic-form/dynamic-form.component.scss
- modules/ui/src/app/components/list-layout/list-layout.component.html
- modules/ui/src/app/pages/devices/devices.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.scss
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.scss
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
- modules/ui/src/styles.scss
Ticket: 391367086
feat: [GM3] add new risk profile form
https://screencast.googleplex.com/cast/NTUzNDUzNzk2OTgyNzg0MHwyODQ4MjkyYy05OQ
> 391367086: (feat) [GM3] add new risk profile form

- modules/ui/src/app/components/list-layout/list-layout.component.ts
Ticket: 391372198
feat: [GM3] add risk profile search
https://screencast.googleplex.com/cast/NjM2NTc3NjMxMDE3MzY5Nnw1NmExOWI2Zi1iYw
> 391372198: (feat) [GM3] add risk profile search

- modules/ui/src/app/mocks/profile.mock.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts
- modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.store.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
- modules/ui/src/styles.scss
Adds copy/delete functionality for Risk Profiles
http://screencast/cast/NDk4MTM0MjU5MTc3ODgxNnxmNWY0M2YwOC03Nw
> Copy/Delete Risk profiles

- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
Fix error when discard acts like cancel
http://screencast/cast/NTg2NDQzODg3MDU3MzA1NnxkYWUwMmI1ZC1iZQ
> [GM3] Devices: Discard acts as Cancel 

- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
- modules/ui/src/app/pages/devices/devices.component.scss
- modules/ui/src/app/pages/devices/devices.component.ts
- modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.html
- modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.scss
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.scss
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
- modules/ui/src/styles.scss
- modules/ui/src/theming/mixins.scss
Ticket: 391372721
feat: add risk profile sticky menu
https://screencast.googleplex.com/cast/NjAxNzEzMTYzNTI3NzgyNHwyNDg2OTU1Yi1mMQ
> 391372721: (feat) add risk profile sticky menu

- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
- modules/ui/src/app/pages/devices/devices.component.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
Ticket: 395664115
fix: [RA] make discard disable until no changes
improve:
remove unnecessary styles in the device form 
fix focus on the devices
https://screencast.googleplex.com/cast/NTU1MDU5ODk2NjQ3NjgwMHw2M2VkY2NkZS1jNg
- devices:
https://screencast.googleplex.com/cast/NTI3NTMyNDU4MDM2NDI4OHwzNTZkY2EzZi0yMw
https://screencast.googleplex.com/cast/NTU5MzA3NzMzMzg4NDkyOHxlZjRkNGE5ZC04Ng
- devices:
https://screencast.googleplex.com/cast/NjExNTc1OTAxNjExNjIyNHxiOThkNTQ3NC1hYQ
> 395664115: (fix) [RA] make discard disable until no changes

- modules/ui/src/app/components/list-item/list-item.component.html
- modules/ui/src/app/components/list-item/list-item.component.ts
- modules/ui/src/app/components/list-layout/list-layout.component.ts
http://screencast/cast/NTk5MzE5MDUxNDQ5MTM5MnwyNDkyMzdmZi02Mw
> Optimize changes detection

- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Ticket: 396579770
fix: set focus to correct interactive elements after delete discard profile
https://screencast.googleplex.com/cast/NjI1MjI5MTU5NzI3MTA0MHw4YjhhMzZlMC1lNA
https://screencast.googleplex.com/cast/NTY5MDQ4NDM3MzU4NTkyMHwyNjk0NmY5NC0zYw
> 396579770: (fix) set focus to correct interactive elements after delete discard profile

- modules/ui/src/app/components/spinner/spinner.component.scss
- modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.html
- modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.scss
- modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.spec.ts
- modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.ts
- modules/ui/src/app/pages/testrun/testrun.component.html
- modules/ui/src/app/pages/testrun/testrun.component.scss
- modules/ui/src/app/pages/testrun/testrun.component.spec.ts
- modules/ui/src/theming/colors.scss
- modules/ui/src/theming/variables.scss
> Adds new design for test run page for statuses before "In progress"

- modules/ui/src/app/components/device-item/device-item.component.scss
- modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.html
- modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.scss
- modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.ts
- modules/ui/src/theming/mixins.scss
- modules/ui/src/theming/variables.scss
Ticket: 396664082:
feat: [GM3] apply changes to start testing modal
https://screenshot.googleplex.com/57dMoMEDhffg4FP
https://screenshot.googleplex.com/A9BHGQ6BuXug2ju
https://screenshot.googleplex.com/9XAqFDxzX2Qyu5F
> 396664082: (feat) [GM3] apply changes to start testing modal

- modules/ui/src/app/components/simple-dialog/simple-dialog.component.scss
- modules/ui/src/app/pages/testrun/testrun.component.html
- modules/ui/src/app/pages/testrun/testrun.component.scss
- modules/ui/src/app/pages/testrun/testrun.component.ts
- modules/ui/src/app/pages/testrun/testrun.store.ts
Adds new style for Stop button; fix style for Stop test run dialog. Small improvement: skip first status to prevent showing the empty state just before actual status
http://screencast/cast/NTIxNzQ5MjEwNzUyNjE0NHwwMWJjMjllZS04OQ
> Stop testing

- modules/test/protocol/python/src/protocol_module.py
Some devices do not respond with their IP address as part of their BACnet discovery response, generally these are virtual devices causing this test to be skipped and report incorrect results.  This removes the IP check from the BACnet version test as this is already accounted for in the BACnet validation step and directly attempts to read the version based on device ip and object id found in the discovery process.
> Fix BACnet version test failures

- modules/test/protocol/python/src/protocol_bacnet.py
Add a message when no BACnet packets are found in protocol.pcap
> No packets found in protocol.pcap

- modules/ui/src/app/model/profile.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
Improve method to check is profile is filled
http://screencast/cast/NDg4ODQwODE1NjUzNjgzMnw2N2YwMjliMS0yMA
> Confirmation popup appears for empty risk profile form when trying to leave the page

- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
http://screencast/cast/NjAxMDIzNTk2NDYyMDgwMHw2MTkwZWU2NC0wOQ
> Delete copy of unsaved profile without backend call

- modules/ui/src/app/mocks/testrun.mock.ts
- modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.html
- modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.scss
- modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.spec.ts
- modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.ts
- modules/ui/src/app/pages/testrun/testrun.component.html
- modules/ui/src/app/pages/testrun/testrun.component.scss
- modules/ui/src/app/pages/testrun/testrun.store.spec.ts
- modules/ui/src/app/pages/testrun/testrun.store.ts
- modules/ui/src/styles.scss
- modules/ui/src/theming/colors.scss
Ticket: 396665821
feat: [GM3] add testing table
https://screencast.googleplex.com/cast/NTk1MDIwOTUwMTY5MTkwNHwwNTU2YzA5Zi00Yg
> 396665821: (feat) [GM3] add testing table

- modules/ui/src/app/components/simple-dialog/simple-dialog.component.html
- modules/ui/src/app/components/simple-dialog/simple-dialog.component.scss
- modules/ui/src/app/components/simple-dialog/simple-dialog.component.spec.ts
- modules/ui/src/app/components/simple-dialog/simple-dialog.component.ts
- modules/ui/src/app/pages/testrun/testrun.component.html
- modules/ui/src/app/pages/testrun/testrun.component.spec.ts
- modules/ui/src/app/pages/testrun/testrun.component.ts
Update design of the Stop Testrun modal
> [GM3] Testing page: text and design for the Stop testrun popup should be changed 

- modules/test/dns/python/src/dns_module.py
If dns.pcap is missing the DNS html report is not generated
> Fix missing dns.pcap

- modules/ui/src/app/pages/testrun/components/test-result-dialog/test-result-dialog.component.html
- modules/ui/src/app/pages/testrun/components/test-result-dialog/test-result-dialog.component.scss
- modules/ui/src/app/pages/testrun/components/test-result-dialog/test-result-dialog.component.spec.ts
- modules/ui/src/app/pages/testrun/components/test-result-dialog/test-result-dialog.component.ts
- modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.spec.ts
- modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.ts
Ticket: 396677540
feat: [GM3] add steps to resolve modal
https://screenshot.googleplex.com/8Lw6Nff3EATunGs
> 396677540: (feat) [GM3] add steps to resolve modal

- modules/ui/src/app/mocks/testrun.mock.ts
- modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.html
- modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.scss
- modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.spec.ts
- modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.ts
- modules/ui/src/app/pages/testrun/testrun.component.html
- modules/ui/src/app/pages/testrun/testrun.component.scss
- modules/ui/src/app/pages/testrun/testrun.component.spec.ts
- modules/ui/src/app/pages/testrun/testrun.component.ts
Ticket: 396676848
feat: [GM3] add testing done
https://screenshot.googleplex.com/6VdBCknpcWAktWH
https://screenshot.googleplex.com/Baj7GuXFE5y3UfV
https://screenshot.googleplex.com/7v9hXukx6CAbJtQ
https://screenshot.googleplex.com/ABeTZ5Th7nUPcwe
https://screenshot.googleplex.com/4oPcVvKssi2RUqY
https://screenshot.googleplex.com/4g2e3Dw8cgdZpPb
> 396676848: (feat) [GM3] add testing done

- modules/ui/src/app/app.component.html
- modules/ui/src/app/app.component.scss
- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/app.component.ts
- modules/ui/src/app/app.store.ts
- modules/ui/src/app/components/list-item/list-item.component.scss
- modules/ui/src/app/components/side-button-menu/side-button-menu.component.html
- modules/ui/src/app/components/side-button-menu/side-button-menu.component.scss
- modules/ui/src/app/components/side-button-menu/side-button-menu.component.spec.ts
- modules/ui/src/app/components/side-button-menu/side-button-menu.component.ts
- modules/ui/src/app/pages/devices/devices.component.spec.ts
- modules/ui/src/app/pages/devices/devices.component.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
- modules/ui/src/app/pages/testrun/testrun.component.ts
- modules/ui/src/app/store/actions.ts
- modules/ui/src/app/store/reducers.ts
- modules/ui/src/app/store/selectors.spec.ts
- modules/ui/src/app/store/selectors.ts
- modules/ui/src/app/store/state.ts
- modules/ui/src/styles.scss
http://screencast/cast/NjUzNzk1NjkxODU1ODcyMHxhM2ZiZWMyYS0xMA
http://screencast/cast/NjY0MzU3NDM5MjIyNTc5Mnw3MzkwNjBlMi03Yg
> Adds side button with menu

- modules/ui/src/app/pages/testrun/components/download-options/download-options.component.html
- modules/ui/src/app/pages/testrun/components/download-options/download-options.component.scss
- modules/ui/src/app/pages/testrun/components/download-options/download-options.component.spec.ts
- modules/ui/src/app/pages/testrun/components/download-options/download-options.component.ts
- modules/ui/src/app/pages/testrun/testrun.component.html
- modules/ui/src/app/pages/testrun/testrun.component.scss
- modules/ui/src/app/pages/testrun/testrun.component.spec.ts
- modules/ui/src/app/pages/testrun/testrun.component.ts
Ticket: 396678430
feat: [GM3] [Testing] add download result options
https://screencast.googleplex.com/cast/NTk5MzE4OTU3NDk2NzI5NnwwNmQ2MTM0Yi01Mg
> 396678430: (feat) [GM3] add download result options

- modules/ui/src/app/interceptors/error.interceptor.ts
- modules/ui/src/app/services/test-run.service.ts
Increase timeout value for /export request
> Report download fails when .zip file is large

- modules/ui/src/app/app.component.html
- modules/ui/src/app/app.component.scss
- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/app.component.ts
- modules/ui/src/app/components/help-tip/help-tip.component.html
- modules/ui/src/app/components/help-tip/help-tip.component.scss
- modules/ui/src/app/components/help-tip/help-tip.component.spec.ts
- modules/ui/src/app/components/help-tip/help-tip.component.ts
- modules/ui/src/app/model/tip-config.ts
- modules/ui/src/styles.scss
Ticket: 403525535
feat: add help tips
https://screencast.googleplex.com/cast/NDcyMjE4NTgwODY0MjA0OHw3ZjcwYWViOS0wZA
> 403525535: (feat) add help tips

- modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.spec.ts
- modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.ts
Focus Version button on Welcome modal close
http://screencast/cast/NjM4MjM3MDUzMjg4NDQ4MHxmZmI5ZDFhZi05Ng
> A11y: The focus doesn't go back to the version button after closing the Welcome modal

- modules/ui/src/app/pages/general-settings/general-settings.component.html
Change tabindex
http://screencast/cast/NjIzNjUxMDYxMjM1NzEyMHxkNzRhYTRjOS01NQ
> A11y: The Refresh link on the general settings page is not accessible  by keyboard

- modules/ui/src/app/app.component.html
- modules/ui/src/app/components/list-layout/list-layout.component.html
> ESC key hides the navigation bar

- modules/ui/src/app/components/side-button-menu/side-button-menu.component.html
> A11y: The Aria attribute doesn't match the role

- modules/ui/src/app/pages/general-settings/general-settings.component.html
- modules/ui/src/app/pages/general-settings/general-settings.component.ts
Enable save button when optout field has changes
http://screencast/cast/NTAzODE5NDIxNDA0MzY0OHw0OWJjMzU2NS0xZA
> The Save button on the Settings page remains inactive if the GA checkbox is selected

- modules/ui/src/app/app.component.ts
- modules/ui/src/app/components/list-item/list-item.component.scss
- modules/ui/src/app/components/list-layout/list-layout.component.scss
- modules/ui/src/app/components/side-button-menu/side-button-menu.component.scss
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
Fix a11y issues on Risk Profiles page
Videos after changes
Mouse
http://screencast/cast/NDYwMjE3MDA2MTA5NDkxMnxkYzk2YTBlYS03NA
Keyboard
http://screencast/cast/NTk3NTgyMDMyNDU2OTA4OHwwNmQwNDliZi1hZg
> The focus issues on the Risk assessment page

- modules/ui/src/app/components/list-layout/list-layout.component.html
- modules/ui/src/app/components/list-layout/list-layout.component.scss
- modules/ui/src/app/pages/devices/devices.component.ts
- modules/ui/src/app/pages/devices/devices.store.ts
Scroll only entities list; focus selected device after save; deselect device after discard
Mouse 
http://screencast/cast/NDYwMjE3MDA2MTA5NDkxMnxkYzk2YTBlYS03NA
Keyboard
http://screencast/cast/NTI0NzAxNTY0NTYwOTk4NHw0ODljNzMwZi1mOA
> The focus issues on the Devices page; The scroll display issue on the Devices page

- modules/ui/src/app/app.component.html
- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/app.component.ts
- modules/ui/src/app/components/help-tip/help-tip.component.spec.ts
- modules/ui/src/app/components/help-tip/help-tip.component.ts
- modules/ui/src/app/model/tip-config.ts
Ticket: 406770411
feat: add start testing message
https://screenshot.googleplex.com/BDfpwEAQpphnxvV
> 406770411: (feat) add start testing message

- modules/ui/src/app/app.component.html
- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/app.component.ts
- modules/ui/src/app/components/help-tip/help-tip.component.html
- modules/ui/src/app/components/help-tip/help-tip.component.scss
- modules/ui/src/app/components/help-tip/help-tip.component.spec.ts
- modules/ui/src/app/model/tip-config.ts
Ticket: 406769857
feat: add risk assessment message
https://screenshot.googleplex.com/9jE8M5skyavQj2w
> 406769857: (feat) add risk assessment message

- modules/ui/src/app/pages/general-settings/components/settings-dropdown/settings-dropdown.component.html
- modules/ui/src/app/pages/general-settings/components/settings-dropdown/settings-dropdown.component.scss
- modules/ui/src/app/pages/general-settings/general-settings.component.html
- modules/ui/src/app/pages/general-settings/general-settings.component.scss
> Fix paddings; change label to placeholder

- modules/ui/src/app/app.component.ts
- modules/ui/src/app/components/list-layout/list-layout.component.ts
Filter navigation buttons to remove "mouse-only" style; clear search input field when user input only spaces
http://screencast/cast/NjU4MzQyNzA2NjIzMjgzMnxiNmQyZTdlZC1kNA
> The search bar issues on Devices and Risk ass-ts pages.

- modules/ui/src/app/mocks/profile.mock.ts
- modules/ui/src/app/services/test-run.service.spec.ts
- modules/ui/src/app/services/test-run.service.ts
http://screencast/cast/NTU2OTEyODUyOTEzMzU2OHwwMTE3MGEyNC0yMA
> Sort profiles list by date

- modules/ui/src/app/app.component.html
- modules/ui/src/app/app.component.spec.ts
- modules/ui/src/app/app.component.ts
Ticket: 409764406
feat: changes to show next tip step on first time user flow
https://screencast.googleplex.com/cast/NTAzODYzOTkzODUzNTQyNHxiNWM4OTI0My1jOQ
> 409764406: (feat) changes to show next tip step on first time user flow

- modules/ui/src/app/app-routing.module.ts
- modules/ui/src/app/guards/can-activate.guard.spec.ts
- modules/ui/src/app/guards/can-activate.guard.ts
Redirect user to settings page if no settings saved
https://screencast.googleplex.com/cast/NjMyNTA2ODY4OTgzMzk4NHw4ZWVlYTlkYy03NA
> First time user: show Settings as first screen

- .github/workflows/package.yml
- README.md
- docs/get_started.md
- docs/virtual_machine.md
Ubuntu 20.04 runner is not supported anymore on Github.
> Removed Ubuntu 20.04 runner

- modules/ui/src/app/pages/testrun/testrun.component.spec.ts
- modules/ui/src/app/pages/testrun/testrun.component.ts
Do not show loading when cancelling
http://screencast/cast/NTE1MDE4NTA4MzYzMzY2NHxiODJmODdjYy1jMg
>  2 loaders are displayed on the Cancelling status

- modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.html
- modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.ts
- modules/ui/src/app/pages/reports/components/filter-header/filter-header.component.ts
Do not show error when only spaces entered
http://screencast/cast/NjE5ODk3ODUwMzc3MDExMnxlOGIyZWE2YS0zMw
> The space entering the Started field causes an error

- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.store.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
- modules/ui/src/app/services/local-storage.service.ts
Scroll to new added profile; remove console.log;
http://screencast/cast/NjIyNDk5Mjk5OTA0NzE2OHxhOGZiYzdkMi1kMg
> Scroll on the RA page when creating new risk profile

- modules/ui/src/app/components/side-button-menu/side-button-menu.component.html
- modules/ui/src/app/components/side-button-menu/side-button-menu.component.spec.ts
- modules/ui/src/app/components/side-button-menu/side-button-menu.component.ts
Close menu and focus menu button on Esc and Tab
http://screencast/cast/NTQ5MTcwMzk3MTU3Nzg1Nnw0ZDFkZjAyNS1iZQ
> The focus disappears if the user goes from the Actions dropdown

- modules/ui/src/app/pages/testrun/components/download-options/download-options.component.html
Change label for download button
Video after changes (sound on)
http://screencast/cast/NTY5MDk2MDEyMDkwNTcyOHw4ZTMwMWJmNi0zYQ
> Screen reader: The button is not announced after clicking the Download button  on the Testing page

- modules/ui/src/app/components/dynamic-form/dynamic-form.component.html
- modules/ui/src/app/components/dynamic-form/dynamic-form.component.scss
- modules/ui/src/app/components/dynamic-form/dynamic-form.component.spec.ts
- modules/ui/src/app/components/dynamic-form/dynamic-form.component.ts
The team of angular material recommends to use one-line hints, so for this case it's better to use approach with script as css changes can break whole component
http://screencast/cast/NjM1NTUwNDI5MTkwNTUzNnwyMDE3NGNmOC0zMg
> Zoom in: the texts on the risk assessment page are overlapped

- modules/test/dns/README.md
- modules/ui/src/app/mocks/testrun.mock.ts
Removed "Any kind of IP multicast" from mdns test
> Remove 'any kind of IP multicast' from mdns test

- modules/ui/src/app/model/testrun-status.ts
- modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.html
- modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.spec.ts
- modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.ts
- modules/ui/src/app/pages/testrun/testrun.component.html
- modules/ui/src/app/store/effects.spec.ts
- modules/ui/src/app/store/effects.ts
Ticket: 413636459 - FF [GM3]: Error occurs on cancelling the test attempt
fix: changes to continue pulling status on cancelling the test
> 413636459: (fix) changes to continue pulling status on cancelling the test

- modules/ui/src/app/components/list-layout/list-layout.component.html
- modules/ui/src/app/components/list-layout/list-layout.component.scss
- modules/ui/src/app/components/list-layout/list-layout.component.spec.ts
- modules/ui/src/app/components/list-layout/list-layout.component.ts
Ticket: 409766621
feat: add clear search button
https://screencast.googleplex.com/cast/NTg3NTM0MTE3NTI5MTkwNHwxNGJlMTk2Ni1jZQ
> 409766621: (feat) add clear search button

- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.store.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
Ticket: 410565507
fix: changes to close form when creating via actions button (for device and risk assessment forms)
https://screencast.googleplex.com/cast/NTQ5NjQ0NjY4OTIxNDQ2NHw2YmVlYTVmNy0zMg
> 410565507: (fix) changes to close form when creating via actions button

- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
Ticket: 410583302
fix: changes for prevent RA disappeared after copy
test: add unit tests
https://screencast.googleplex.com/cast/NTkzNzIwNzIzODk4MzY4MHw0MTk5NTMwMi04Yw
> 410583302: (fix) changes for prevent RA disappeared after copy

- modules/ui/src/app/pages/devices/devices.component.html
- modules/ui/src/app/pages/devices/devices.component.ts
Change menu for outdated device
> The Outdated device has the option "Start new Testrun" enabled.

- modules/ui/src/app/components/list-item/list-item.component.html
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
- modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Ticket: 421375877
fix: remove actions menu for copy profile
https://screencast.googleplex.com/cast/NTE5ODAyMjk2NjI0NzQyNHw1ZTFhMmViMi1hMw
> 421375877: (fix) remove actions menu for copy profile

- modules/ui/src/app/mocks/profile.mock.ts
- modules/ui/src/app/model/profile.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
- modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts
- modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Adds new status for easier profile management
http://screencast/cast/NjM2NDIwNTU3MjY4NTgyNHxmYTYxZWUxYi1iYQ
Copy of profile
http://screencast/cast/NjcxOTU3MzkxODIyMDI4OHw4NDg1NGRhMi02YQ
> The Discard popup appears if no changes were made in the profile

- modules/ui/src/app/components/help-tip/help-tip.component.ts
- modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
- modules/ui/src/app/pages/devices/devices.component.ts
Get updated tip element after timeout to prevent focus previous (undefined) tip
http://screencast/cast/Njc1MDE2Mjg0MzA3NDU2MHwyYjFhNTkwOS03MQ
> A11y: the focus is not moved to the first user flow guide message for the step 3

- modules/ui/src/app/components/device-item/device-item.component.html
- modules/ui/src/app/components/list-item/list-item.component.ts
Fix tooltips
Screenshots after changes
https://screenshot.googleplex.com/5cMvYWS9wauxC7r
https://screenshot.googleplex.com/7DoDQX3eRKW5bjD
> A11y: The hover tooltip is not implemented for the devices and risk profile tiles

- modules/test/tls/python/src/http_scan.py
Change HTTPS detection method
returns three messages: HTTP, HTTPS, UNKNOWN
Timeout expanded to 5 seconds
> refactor https_detect
