google/testrun

modules/test/nmap/python/src/nmap_module.py
Removes the duplicate port number from the nmap module results.
=> Fix duplicate port number

framework/python/src/common/device.py, framework/python/src/common/testreport.py, framework/python/src/common/util.py
=> Add device configuration to PDF report

modules/network/base/bin/capture, modules/test/base/bin/capture
Resolves issue: https://github.com/google/testrun/issues/149
=> Close capture files correctly

modules/test/ntp/python/src/ntp_module.py
Add NTP server network captures to NTP traffic scan
=> NTP Capture Files

.github/workflows/testing.yml, modules/ui/src/app/components/device-item/device-item.component.scss
Video after changes 
https://screencast.googleplex.com/cast/NjUxMzQ5NTQ0NDAyOTQ0MHwyNTBhOGRlZC1lNQ
=> Fix styles for helperbird

.github/workflows/testing.yml, modules/ui/tsconfig.json
=> Adds ESLint workflow

modules/ui/src/app/services/notification.service.spec.ts, modules/ui/src/app/services/notification.service.ts
=> Set snack bar duration to 0 to prevent auto closing

modules/ui/src/app/app.module.ts, modules/ui/src/app/pages/settings/general-settings.component.ts
https://screencast.googleplex.com/cast/NTIyMzQ4MDMyMzczNTU1MnxiMGQwZmI0Yi1mMw
=> Adds trap focus on connection settings panel

modules/ui/package-lock.json, modules/ui/package.json, modules/ui/src/app/app.component.html, modules/ui/src/app/app.component.spec.ts, modules/ui/src/app/app.component.ts, modules/ui/src/app/app.module.ts, modules/ui/src/app/mocks/settings.mock.ts, modules/ui/src/app/model/setting.ts, modules/ui/src/app/pages/settings/components/settings-dropdown/settings-dropdown.component.html, modules/ui/src/app/pages/settings/components/settings-dropdown/settings-dropdown.component.scss, modules/ui/src/app/pages/settings/components/settings-dropdown/settings-dropdown.component.spec.ts, modules/ui/src/app/pages/settings/components/settings-dropdown/settings-dropdown.component.ts, modules/ui/src/app/pages/settings/general-settings.component.html, modules/ui/src/app/pages/settings/general-settings.component.scss, modules/ui/src/app/pages/settings/general-settings.component.spec.ts, modules/ui/src/app/pages/settings/general-settings.component.ts, modules/ui/src/app/pages/settings/only-different-values.validator.ts, modules/ui/src/app/pages/settings/settings.store.spec.ts, modules/ui/src/app/pages/settings/settings.store.ts, modules/ui/src/app/store/actions.ts, modules/ui/src/app/store/effects.spec.ts, modules/ui/src/app/store/effects.ts, modules/ui/src/app/store/reducers.spec.ts, modules/ui/src/app/store/reducers.ts, modules/ui/src/app/store/selectors.spec.ts, modules/ui/src/app/store/selectors.ts, modules/ui/src/app/store/state.ts
- adds component store
- move dropdowns to separate component
=> Refactoring

modules/ui/src/app/services/test-run.service.ts
Sets the API url within the UI so that Testrun can be accessed on remote machines.
=> Change URL used by UI

modules/ui/src/app/model/testrun-status.ts, modules/ui/src/app/services/test-run.service.spec.ts, modules/ui/src/app/services/test-run.service.ts
**Ticket:** 324383967
**feat:** display in progress test status
**tests:** update unit tests
=> 324383967: (feat) display in progress test status

modules/ui/src/app/components/spinner/spinner.component.spec.ts, modules/ui/src/app/model/testrun-status.ts, modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.ts, modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.spec.ts, modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.ts, modules/ui/src/app/services/test-run.service.spec.ts, modules/ui/src/app/services/test-run.service.ts
Ticket: 322355032
feat: add high and limited compliant test statuses (testrun, results pages and filters)
tests: add, improve Unit tests
=> 322355032: (feat) add high and limited compliant test statuses

modules/ui/src/app/mocks/reports.mock.ts, modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.spec.ts, modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.ts, modules/ui/src/app/pages/reports/history.component.html, modules/ui/src/app/pages/reports/history.component.spec.ts, modules/ui/src/app/pages/reports/history.component.ts, modules/ui/src/app/pages/reports/reports.store.spec.ts, modules/ui/src/app/pages/reports/reports.store.ts, modules/ui/src/app/services/test-run.service.spec.ts, modules/ui/src/app/services/test-run.service.ts
Video after changes (works as same as before)
http://screencast/cast/NjIzOTQ2OTkzNzA5ODc1MnxjYjBkNzc3OS04Zg
=> Adds component state for reports page

modules/ui/src/app/pages/testrun/components/progress-table/progress-table.component.scss
**Ticket:** 325419639: 
**fix:** [a11y] change styles for meet GAR 2.11 for the arrow button for expanding Steps to resolve
=> 325419639: (fix) [a11y] change styles for meet GAR 2.11 for the arrow button

modules/ui/src/app/components/device-item/device-item.component.scss
**Ticket:** 324202752 
**fix:** device name and device model name cutting
=> 324202752: (fix) device name and device model name cutting

modules/ui/src/app/app.component.html, modules/ui/src/app/app.component.spec.ts, modules/ui/src/app/app.component.ts, modules/ui/src/app/pages/settings/general-settings.component.ts
=> Update interfaces on settings open

modules/ui/src/app/app.component.html, modules/ui/src/app/app.component.spec.ts, modules/ui/src/app/app.component.ts, modules/ui/src/app/app.store.spec.ts, modules/ui/src/app/app.store.ts, modules/ui/src/app/components/version/version.component.ts
http://screencast/cast/NTI0NzM4MDAwNDc5ODQ2NHwwYmYxZmIyZS1hMA
Tests
=> Show consent dialog only once per session

modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.html, modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.scss
=> Fix text; fix gaps

modules/ui/src/styles.scss
https://screencast.googleplex.com/cast/NDg2OTUyMTMzMTQ1Mzk1Mnw1OGUyZWRkNi1mNg
=> Fix focus style when consent pop-up closed

modules/ui/src/app/app.component.html, modules/ui/src/app/app.component.spec.ts, modules/ui/src/app/app.component.ts, modules/ui/src/app/app.store.spec.ts, modules/ui/src/app/app.store.ts, modules/ui/src/app/mocks/device.mock.ts, modules/ui/src/app/pages/devices/components/device-form/device-form.component.spec.ts, modules/ui/src/app/pages/devices/components/device-form/device-form.component.ts, modules/ui/src/app/pages/devices/components/device-form/device.validators.ts, modules/ui/src/app/pages/devices/device-repository.component.html, modules/ui/src/app/pages/devices/device-repository.component.spec.ts, modules/ui/src/app/pages/devices/device-repository.component.ts, modules/ui/src/app/pages/devices/devices.store.spec.ts, modules/ui/src/app/pages/devices/devices.store.ts, modules/ui/src/app/pages/testrun/components/progress-initiate-form/progress-initiate-form.component.spec.ts, modules/ui/src/app/pages/testrun/components/progress-initiate-form/progress-initiate-form.component.ts, modules/ui/src/app/pages/testrun/progress.component.html, modules/ui/src/app/pages/testrun/progress.component.spec.ts, modules/ui/src/app/pages/testrun/progress.component.ts, modules/ui/src/app/services/test-run.service.spec.ts, modules/ui/src/app/services/test-run.service.ts, modules/ui/src/app/store/actions.ts, modules/ui/src/app/store/effects.spec.ts, modules/ui/src/app/store/effects.ts, modules/ui/src/app/store/reducers.spec.ts, modules/ui/src/app/store/reducers.ts, modules/ui/src/app/store/selectors.spec.ts, modules/ui/src/app/store/selectors.ts, modules/ui/src/app/store/state.ts
=> Adds state for devices component; devices added to shared state

modules/ui/src/app/services/test-run.service.spec.ts, modules/ui/src/app/services/test-run.service.ts
**Ticket:** 327410289
**feat:** add protocol module
=> 327410289: (feat) add protocol module

modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.ts
**Ticket:** 327324282
**fix:** remove compliant high and limited statuses from filters
=> 327324282: (fix) remove compliant high and limited statuses from filters

modules/ui/src/app/services/test-run.service.spec.ts, modules/ui/src/app/services/test-run.service.ts
**Ticket:** 327722371
**fix:** make the Welcome modal appears in case the version response returns the error
https://screencast.googleplex.com/cast/NTk1MDczMjAwMjkxODQwMHw2YWMwYTFjMi1hZQ
https://screencast.googleplex.com/cast/NTQzMjQ5OTQwMzQ4OTI4MHwyM2U3NjAyZC1mYw
=> 327722371 (fix) make the Welcome modal appears in case the version response returns the error

modules/ui/src/app/app.component.html, modules/ui/src/app/app.component.spec.ts, modules/ui/src/app/app.component.ts, modules/ui/src/app/model/setting.ts, modules/ui/src/app/store/actions.ts, modules/ui/src/app/store/effects.spec.ts, modules/ui/src/app/store/effects.ts, modules/ui/src/app/store/reducers.spec.ts, modules/ui/src/app/store/reducers.ts, modules/ui/src/app/store/selectors.spec.ts, modules/ui/src/app/store/selectors.ts, modules/ui/src/app/store/state.ts
**Ticket:** 327324281
feat: change callout messages for missing setting ports
=> 327324281: (feat) change callout messages for missing setting ports

modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.ts
Remove consent dialog close on esc
=> Consent dialog should not be closed on esc

modules/ui/src/app/app.component.scss, modules/ui/src/styles.scss
http://screencast/cast/NTUxNzczMTExNjg3NTc3Nnw5NmM3YTI1My05ZQ
=> Fix padding in menu item

modules/ui/src/app/pages/testrun/progress.component.scss
=> Change progress page spinner size to small

modules/ui/src/app/components/download-report-pdf/download-report-pdf.component.html, modules/ui/src/app/components/download-report-pdf/download-report-pdf.component.spec.ts, modules/ui/src/app/components/download-report-pdf/download-report-pdf.component.ts, modules/ui/src/app/components/download-report-zip/download-report-zip.component.html, modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts, modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts, modules/ui/src/app/pages/reports/history.component.html, modules/ui/src/app/pages/reports/history.component.scss, modules/ui/src/app/pages/reports/history.component.spec.ts, modules/ui/src/app/pages/reports/history.module.ts, modules/ui/src/app/pages/testrun/progress.component.html, modules/ui/src/app/pages/testrun/progress.component.spec.ts, modules/ui/src/app/pages/testrun/progress.module.ts
Adds zip report button; added new component; update old component
=> Zip report

modules/ui/src/app/components/version/version.component.html, modules/ui/src/app/components/version/version.component.spec.ts, modules/ui/src/app/components/version/version.component.ts
**Ticket:** 329086273
**fix:** [a11Y] change the version button accessible name
=> 329086273: (fix) [a11Y] change the version button accessible name

framework/python/src/net_orc/network_orchestrator.py, framework/python/src/test_orc/test_orchestrator.py
- Add system.json to runtime/conf folder
- Add device_config.json to runtime/test/{mac addr}
- Zip entire runtime folder to include conf and network folder
=> Zip report updates

framework/python/src/api/api.py, framework/python/src/common/device.py, framework/python/src/common/testreport.py, framework/python/src/common/util.py, framework/python/src/net_orc/network_orchestrator.py, framework/python/src/net_orc/network_validator.py, framework/python/src/test_orc/test_orchestrator.py, modules/test/conn/python/src/connection_module.py, testing/pylint/test_pylint
- Unable to recreate this issue so this adds additional reporting to help identify root cause https://github.com/google/testrun/issues/261
- Fix outstanding pylint issues and update expected error count
=> improve pylint score

modules/ui/src/app/components/device-item/device-item.component.scss, modules/ui/src/app/components/download-report/download-report.component.scss, modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.scss, modules/ui/src/app/pages/reports/history.component.scss, modules/ui/src/app/pages/testrun/components/progress-table/progress-table.component.scss, modules/ui/src/app/pages/testrun/progress.component.scss
**Ticket:** 330700777
**fix:** update styles for fixing ui focus border issues on testing page table, device item, report page table actions (download, delete)
Link: https://screencast.googleplex.com/cast/NjQ0ODkzMjc0MDY2MTI0OHxkNzRiNmZkNy1iZA
=> 330700777: (fix) update styles for fixing ui focus border issues

modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.html
**Ticket:** 331364084
**fix:** update label and placeholder for started modal filter
=> 331364084: (fix) update label and placeholder for started modal filter

modules/ui/src/app/components/device-item/device-item.component.scss, modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.scss
**Ticket:** 328745809
**fix: [a11y]** change styles to status card and device item or meet requirements dyslexia
=> 328745809: (fix) [a11y] change styles to status card and device item or meet requirements dyslexia

modules/test/base/base.Dockerfile
- Update oui cache file
- Fix download command
=> Fix OUI download bug

modules/ui/src/app/app.component.html, modules/ui/src/app/app.component.spec.ts, modules/ui/src/app/app.component.ts, modules/ui/src/app/app.store.spec.ts, modules/ui/src/app/app.store.ts, modules/ui/src/app/pages/testrun/components/progress-initiate-form/progress-initiate-form.component.html, modules/ui/src/app/pages/testrun/components/progress-initiate-form/progress-initiate-form.component.spec.ts, modules/ui/src/app/pages/testrun/components/progress-initiate-form/progress-initiate-form.component.ts, modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.html, modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.spec.ts, modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.ts, modules/ui/src/app/pages/testrun/components/progress-table/progress-table.component.html, modules/ui/src/app/pages/testrun/components/progress-table/progress-table.component.spec.ts, modules/ui/src/app/pages/testrun/components/progress-table/progress-table.component.ts, modules/ui/src/app/pages/testrun/progress.component.html, modules/ui/src/app/pages/testrun/progress.component.spec.ts, modules/ui/src/app/pages/testrun/progress.component.ts, modules/ui/src/app/pages/testrun/testrun.store.spec.ts, modules/ui/src/app/pages/testrun/testrun.store.ts, modules/ui/src/app/services/test-run.service.spec.ts, modules/ui/src/app/services/test-run.service.ts, modules/ui/src/app/store/actions.ts, modules/ui/src/app/store/reducers.spec.ts, modules/ui/src/app/store/reducers.ts, modules/ui/src/app/store/selectors.spec.ts, modules/ui/src/app/store/selectors.ts, modules/ui/src/app/store/state.ts
http://screencast/cast/NTQ2MzUwODYzMTE1ODc4NHxhNWUyMzlmYi1lNA
=> Adds testrun component state

cmd/package, framework/python/src/common/testreport.py, make/DEBIAN/control, modules/test/base/python/src/test_module.py, modules/test/protocol/python/src/protocol_modbus.py
Fix modbus test crash when compliant
=> Hotfix 1.2.1

modules/ui/src/app/model/testrun-status.ts, modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.spec.ts, modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.ts, modules/ui/src/app/services/test-run.service.spec.ts, modules/ui/src/app/services/test-run.service.ts
Ticket: 332883321
feat: add support for Feature Not Present and Error statuses
=> 332883321: (feat) add support for Feature Not Present and Error statuses

modules/ui/src/app/pages/testrun/components/download-options/download-options.component.html, modules/ui/src/app/pages/testrun/components/download-options/download-options.component.scss, modules/ui/src/app/pages/testrun/components/download-options/download-options.component.spec.ts, modules/ui/src/app/pages/testrun/components/download-options/download-options.component.ts, modules/ui/src/app/pages/testrun/progress.component.html, modules/ui/src/app/pages/testrun/progress.component.spec.ts, modules/ui/src/app/pages/testrun/progress.module.ts
Ticket: 333723882
feat: add download options on testing page
Link: https://screencast.googleplex.com/cast/NjY4NzY5Nzc5MDgyODU0NHxkMTlmY2YwYy1hNg
=> 333723882: (feat) add download options on testing page

modules/ui/src/app/app.component.scss, modules/ui/src/app/pages/reports/history.component.scss, modules/ui/src/styles.scss
Scrolls on side bar
https://screencast.googleplex.com/cast/NDc0NjY3NjM3NDg2Mzg3MnxjZDk5ZDVlZi1jMg
Scroll on reports table
https://screencast.googleplex.com/cast/NDk1NTI1ODM5OTc1MjE5MnxjZjM3NzMyMS0yMA
=> Fix scrolls for mozilla

modules/ui/src/app/pages/reports/history.component.scss
Ticket: 336737453
fix: the reports table is not fitting the content
https://screencast.googleplex.com/cast/NjY3OTc5ODA3MDkwMjc4NHw5ODgzZDA5NS00ZA
https://screencast.googleplex.com/cast/NDYzOTEwNDQ4OTc1MDUyOHwwN2E5NTVlZS04YQ
=> 336737453: (fix) the reports table is not fitting the content

modules/ui/src/app/pages/testrun/components/download-options/download-options.component.html, modules/ui/src/app/pages/testrun/components/download-options/download-options.component.scss
Ticket: 336268076
fix: change borders for the button and options in download dropdown
Link: https://screencast.googleplex.com/cast/NDY4NjMwMTA0NjUwNTQ3MnxhZWViMTkwZC01ZQ
=> 336268076: (fix) change borders for the button and options in download dropdown

modules/ui/src/app/pages/devices/device-repository.component.html, modules/ui/src/app/pages/devices/device-repository.component.spec.ts
http://screencast/cast/NDk1MTc5NDc1MTg5NzYwMHw4OWMzYThhNS0yNA
=> Fix mac_address validation

modules/ui/src/app/pages/testrun/progress.component.ts
=> Fix function return value

modules/ui/src/app/pages/devices/device-repository.component.spec.ts, modules/ui/src/app/pages/devices/device-repository.component.ts
http://screencast/cast/NTE2MTQyMjQ0MTkzODk0NHxiMjU1NTAyYi0zMA
=> Fix redirect + adds google analytics

modules/ui/src/app/pages/reports/history.component.scss
=> Change paddings depends on table width

modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.html, modules/ui/src/app/pages/testrun/components/progress-status-card/progress-status-card.component.spec.ts
http://screencast/cast/NDY3OTM1OTAwMzYyMzQyNHxhMjQ3MTc4NS1mNw
Tests
=> In progress test result

framework/python/src/api/api.py, framework/python/src/common/testreport.py
See attached PDF
[2024-04-09T13_09_48.pdf](https://github.com/google/testrun/files/14918718/2024-04-09T13_09_48.pdf)
=> Fixes defects in the PDF report if a long device name is specified

modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.scss
=> Fix button size; fix text-overflow

modules/ui/src/app/model/testrun-status.ts, modules/ui/src/app/services/test-run.service.spec.ts, modules/ui/src/app/services/test-run.service.ts
fix: replace Feature Not Present to Feature Not Detected
=> fix: replace Feature Not Present to Feature Not Detected

framework/python/src/common/testreport.py, framework/python/src/common/util.py
See attached.
[report.pdf](https://github.com/google/testrun/files/15259763/report.pdf)
=> Fix alignment with steps to resolve in PDF report

modules/ui/src/app/pages/certificates/certificate-upload-button/certificate-upload-button.component.scss, modules/ui/src/styles.scss
http://screencast/cast/NTUwMjc5NDM2MTQ3MDk3NnxmYzlmN2E2My1iMg
=> UI defects are shown while using increased text spacing

modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.scss, modules/ui/src/styles.scss, modules/ui/src/theming/variables.scss
Ticket: 340835710
fix: [Risk assessment] change page view when callout is visible
####with callout different types:
https://screenshot.googleplex.com/9Uzc3uRREk3AwFj
https://screenshot.googleplex.com/AbppumXu5CamR39
https://screenshot.googleplex.com/3X2S5ajoRLzE4ZP
https://screenshot.googleplex.com/5Hd9ipBKHdkqLX8
https://screenshot.googleplex.com/AM72p8nzfMyjVqa
=> 340835710: (fix) [Risk assessment] change page view when callout is visible

modules/ui/src/app/pages/risk-assessment/risk-assessment.component.scss
Ticket: 341901606
fix: [GAR 1.6] update styles to prevent unnecessary scroll for arrows usage on risk profile
https://screencast.googleplex.com/cast/NjM2NzMzNTg2OTg0MTQwOHxlMDU5ZDY1Yy01ZQ
https://screencast.googleplex.com/cast/NjQzMzIxMTEzODcwMzM2MHxmNjc0YzVmMC1hZQ
=> 341901606: (fix) [GAR 1.6]: update for arrows usage on risk profile

modules/ui/src/app/pages/certificates/certificates.component.ts
Ticket: 342096458
fix: [GAR 1.3] add focus trap to certificates panel to prevent move focus to risk profile
https://screencast.googleplex.com/cast/NjA2NDMzMTI5NTgxNzcyOHwzZjg2MTczZC1lYw
https://screencast.googleplex.com/cast/NjE5NjM3NTg3OTQxNzg1Nnw3NjM1YWE4NC0zZg
=> 342096458: (fix) [GAR 1.3] add focus trap to certificates panel to prevent move focus to risk profile

modules/ui/src/app/pages/certificates/certificates.component.ts, modules/ui/src/app/pages/certificates/certificates.store.spec.ts, modules/ui/src/app/pages/certificates/certificates.store.ts
=> Adds file name in error message

modules/ui/src/app/app.component.spec.ts, modules/ui/src/app/app.store.spec.ts, modules/ui/src/app/pages/testrun/progress.component.ts, modules/ui/src/app/pages/testrun/testrun.store.spec.ts, modules/ui/src/app/pages/testrun/testrun.store.ts, modules/ui/src/app/store/effects.spec.ts, modules/ui/src/app/store/effects.ts
Make waiting for device snackbar global
=> "Waiting for Device" :the snack bar appears on all pages

modules/ui/src/app/pages/certificates/certificates.store.spec.ts, modules/ui/src/app/pages/certificates/certificates.store.ts
Before
https://screencast.googleplex.com/cast/NTYyMTMxODMwNDEzNzIxNnxmZDU1MmViZS1lYg
After
https://screencast.googleplex.com/cast/NDYyMTg3MzAzOTAxNTkzNnw4MDY0MGYxMy0yNg
Tests
=> Remove certificate if BE error happens

modules/ui/src/app/components/snack-bar/snack-bar.component.spec.ts, modules/ui/src/app/components/snack-bar/snack-bar.component.ts, modules/ui/src/app/pages/testrun/testrun.component.spec.ts, modules/ui/src/app/pages/testrun/testrun.component.ts, modules/ui/src/app/pages/testrun/testrun.store.spec.ts, modules/ui/src/app/pages/testrun/testrun.store.ts, modules/ui/src/app/services/notification.service.ts, modules/ui/src/app/store/actions.ts, modules/ui/src/app/store/effects.spec.ts, modules/ui/src/app/store/effects.ts, modules/ui/src/app/store/reducers.spec.ts, modules/ui/src/app/store/reducers.ts, modules/ui/src/app/store/selectors.spec.ts, modules/ui/src/app/store/selectors.ts
video after changes
http://screencast/cast/NjMxOTUyMTQ3NTMzMDA0OHxiOGZhZjQwNi03Nw
=> Allow stop testrun from any other page

modules/ui/src/app/app.component.html, modules/ui/src/app/app.component.spec.ts, modules/ui/src/app/app.component.ts, modules/ui/src/app/app.store.spec.ts, modules/ui/src/app/app.store.ts, modules/ui/src/app/components/callout/callout.component.scss, modules/ui/src/app/model/callout-type.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.store.spec.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts, modules/ui/src/app/store/actions.ts, modules/ui/src/app/store/effects.spec.ts, modules/ui/src/app/store/effects.ts, modules/ui/src/app/store/reducers.spec.ts, modules/ui/src/app/store/reducers.ts, modules/ui/src/app/store/selectors.spec.ts, modules/ui/src/app/store/selectors.ts, modules/ui/src/app/store/state.ts, modules/ui/src/styles.scss
Ticket: 342365574
feat: display info about Risk Assessment during testing
https://screenshot.googleplex.com/6Ho3Vq7UkQrVBT3
https://screenshot.googleplex.com/6i52UENPhwdYghZ
=> 342365574: (feat) display info about Risk Assessment during testing

modules/ui/src/app/components/download-report-zip/download-report-zip.component.html, modules/ui/src/app/components/download-report-zip/download-report-zip.component.scss, modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts, modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts, modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html, modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.scss, modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.spec.ts, modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.ts, modules/ui/src/app/pages/reports/reports.component.html, modules/ui/src/app/pages/reports/reports.component.spec.ts, modules/ui/src/app/pages/reports/reports.store.spec.ts, modules/ui/src/app/pages/reports/reports.store.ts, modules/ui/src/app/pages/testrun/components/download-options/download-options.component.html, modules/ui/src/app/pages/testrun/components/download-options/download-options.component.scss, modules/ui/src/app/pages/testrun/components/download-options/download-options.component.spec.ts, modules/ui/src/app/pages/testrun/components/download-options/download-options.component.ts, modules/ui/src/app/pages/testrun/testrun.component.html, modules/ui/src/app/pages/testrun/testrun.component.spec.ts, modules/ui/src/app/pages/testrun/testrun.store.spec.ts, modules/ui/src/app/pages/testrun/testrun.store.ts, modules/ui/src/app/services/test-run.service.spec.ts, modules/ui/src/app/services/test-run.service.ts
video after changes 
https://screencast.googleplex.com/cast/NDUyNDM2NzkyODA5ODgxNnw3OTdlNThlYy0zYw
=> Adds download zip window

modules/ui/src/app/store/effects.spec.ts, modules/ui/src/app/store/effects.ts
Ticket: 344874424
fix: disable device tile in Canceling status
https://screencast.googleplex.com/cast/NTEwMjM2Mzg0ODIxMjQ4MHw0YjhjNjllYy1kOA
https://screenshot.googleplex.com/7uooBDqZJ6jZyur
=> 344874424: (fix) disable device tile in Canceling status

modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.html, modules/ui/src/index.html
=> GA option issues on the Welcome modal

modules/ui/src/app/app.component.html, modules/ui/src/app/app.component.ts
Ticket: 345202815
fix: update to prevent callout with the RA message is shown on the RA page
https://screencast.googleplex.com/cast/NjM5NzkzNTc0MTgyOTEyMHw5YjM5MGJlZC0yMg
=> 345202815: (fix) callout with the RA message is shown on the RA page

modules/ui/src/app/app.component.html, modules/ui/src/app/app.component.spec.ts, modules/ui/src/app/app.component.ts
=> Announce disabled state of settings panel

modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html, modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.scss, modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts, modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts, modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.scss, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.module.ts
Ticket: 340859666
feat: display risk profile form with name field
https://screencast.googleplex.com/cast/NTQ0Mzg3Mjg3MTE1MzY2NHwzM2UxNzBjZi0zNA
https://screenshot.googleplex.com/AsSopt7JLEXV57E
https://screenshot.googleplex.com/9GVWwsWq5XSrAmm
https://screenshot.googleplex.com/Bt98QtBGALRZpYr
https://screenshot.googleplex.com/6496YGrhPs3T9Dv
=> 340859666: (feat): display risk profile form with name field

framework/python/src/api/api.py, modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts, modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts, modules/ui/src/app/pages/reports/reports.component.html, modules/ui/src/app/services/test-run.service.spec.ts, modules/ui/src/app/services/test-run.service.ts
Stop propagating event to eliminate the error
"+" fix tooltip
=> The Downlaod ZIP action can not be performed using the keyboard

modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts, modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts, modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts
http://screencast/cast/NTc3NTMyNTU2MzcxNTU4NHw2ODAwOWY0MC1lZg
Tests
=> Mark fields required when trimmed value is empty

modules/ui/src/app/pages/reports/reports.component.scss
=> Fix scroll area on reports page

modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
https://screencast.googleplex.com/cast/NTUzNTU4MTg5ODUzOTAwOHwyZjQ1Mzk4ZC0xNA
=> Announce risk form open; focus first element in container

modules/ui/src/app/model/certificate.ts, modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.html, modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.scss, modules/ui/src/app/pages/certificates/certificate-item/certificate-item.component.ts
Ticket: 345258435
feat: display expired certificate
https://screenshot.googleplex.com/5JCET5ogRokTena
=> 345258435: (feat) display expired certificate

modules/ui/src/app/components/callout/callout.component.scss
Ticket: 348187954
fix: update callouts position on the small window size
https://screencast.googleplex.com/cast/NjE4Njk5MTkzNzkxMjgzMnxjZjdiNDViNC0yNg
=> 348187954: (fix) update callouts position on the small window size

modules/ui/src/app/app.component.html, modules/ui/src/app/app.module.ts, modules/ui/src/app/components/device-item/device-item.component.html, modules/ui/src/app/components/device-item/device-item.component.ts, modules/ui/src/app/components/shutdown-app/shutdown-app.component.html, modules/ui/src/app/components/shutdown-app/shutdown-app.component.ts
Ticket: 348356236
fix: add tooltips for icons without any accompanying text
https://screencast.googleplex.com/cast/NTkxOTQ4MTc3ODkyOTY2NHwzYzg1OWIyOC1mYg
=> 348356236: (fix) add tooltips for icons without any accompanying text

modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts, modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts
Ticket: 348353479
fix: add tooltip for the download zip button using the keyboard
https://screencast.googleplex.com/cast/NTk0NzIzNzMzMzk5MTQyNHwwOTUwYjk0Yi0zYw
https://screencast.googleplex.com/cast/Njc1MDY2OTY4Njk2NDIyNHw2MzE0OTBhNC05ZA
=> 348353479: (fix) add tooltip for the download zip button using the keyboard

modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html
Ticket: 348361925
fix: add helper text for mandatory profile name field
https://screenshot.googleplex.com/7iiYwAmsXh4WZyg
=> 348361925: (fix) add helper text for mandatory profile name field

modules/test/dns/python/src/dns_module.py
Fix DNS report when DNS packet is missing the qname property
=> DNS report failure

modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.spec.ts, modules/ui/src/app/components/simple-dialog/simple-dialog.component.html, modules/ui/src/app/components/simple-dialog/simple-dialog.component.scss, modules/ui/src/app/components/simple-dialog/simple-dialog.component.spec.ts, modules/ui/src/app/components/simple-dialog/simple-dialog.component.ts, modules/ui/src/app/mocks/profile.mock.ts, modules/ui/src/app/model/profile.ts, modules/ui/src/app/pages/certificates/certificates.component.spec.ts, modules/ui/src/app/pages/certificates/certificates.component.ts, modules/ui/src/app/pages/devices/devices.component.spec.ts, modules/ui/src/app/pages/devices/devices.component.ts, modules/ui/src/app/pages/devices/devices.module.ts, modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.spec.ts, modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.ts, modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html, modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts, modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts, modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.spec.ts, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.store.spec.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts, modules/ui/src/app/pages/testrun/testrun.component.spec.ts, modules/ui/src/app/pages/testrun/testrun.component.ts, modules/ui/src/app/services/test-run.service.ts
Tests
https://screencast.googleplex.com/cast/Njc0NzQ4Nzk4ODYxMzEyMHxjMjY1NjBjMi01YQ
=> Adds edit risk profile

modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html, modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
Before 
http://screencast/cast/NTE0MjM4NTQ5NDMyNzI5Nnw3ZjUwODUwMy04YQ
After
http://screencast/cast/NjY5NzQxODkzNzU5Nzk1MnxkZTQyYzZhMy0xZg
=> Fix autozise

modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html, modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.scss, modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.spec.ts, modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.ts, modules/ui/src/app/model/profile.ts, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.spec.ts, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.ts, modules/ui/src/app/services/test-run.service.spec.ts, modules/ui/src/app/services/test-run.service.ts, modules/ui/src/styles.scss, modules/ui/src/theming/colors.scss
Ticket: 346351108
feat: display risk assessment result
https://screenshot.googleplex.com/3oCjQ2aG5HopUqc
https://screenshot.googleplex.com/8avLKJZu346x7e6
https://screenshot.googleplex.com/BTKfuYhaqdghFVK
=> 346351108: (feat) display risk assessment result

modules/ui/src/app/pages/reports/reports.component.scss
Ticket: 349769454
fix: update size on the empty reports page to prevent overlapping
https://screenshot.googleplex.com/8Mju9pQ59mtKvvZ
https://screenshot.googleplex.com/3cLxevc3yh2tVnF
=> 349769454: (fix) update size on the empty reports page to prevent overlapping

modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.scss, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.scss, modules/ui/src/theming/colors.scss
Ticket: 349783464
fix (styles): add styles for highlighting selected profile on RA
fix (styles): fix form size on RA (some fields were not full width)
https://screenshot.googleplex.com/7pP5xsrfSW5v3PY
https://screencast.googleplex.com/cast/NTI0MDc3NjI4Mjg2NTY2NHxlZjc5ZjllYy1mMw
https://screencast.googleplex.com/cast/NTY5Nzc1MTgxMDU3MjI4OHxmNzZkZGQxMy0zOQ
=> 349783464: (fix) add styles for selected elements and fix form size on RA

modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Ticket: 349793005
fix: change focus to profile form to scroll up on opening profile
https://screencast.googleplex.com/cast/NjE3MjgwNzYwNzA5MTIwMHxkMDNlZDAwYy1lNg
https://screencast.googleplex.com/cast/NTIzMjMxMjcxNDI2NDU3NnwxZTkxODYzMC1kNQ
=> 349793005: (fix) change focus to profile form to scroll up on opening profile

modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html, modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
Tests
http://screencast/cast/NTAzMjI5NjAyMDE4MDk5MnwwYmUzZDhhNS00Nw
=> Enables save and draft button for edit mode

modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html, modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts, modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
Validate multi select form group on last checkbox tab press
Tests
http://screencast/cast/NTYyNTkwMTkwNjY1NzI4MHwzZDc5ZmNkMi04MA
=>  The validation for the multi-select questions is not shown

modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.spec.ts
=> Remove copy button

modules/ui/src/app/app.component.html, modules/ui/src/app/app.component.ts, modules/ui/src/app/app.store.spec.ts, modules/ui/src/app/app.store.ts, modules/ui/src/app/pages/devices/devices.component.html, modules/ui/src/app/pages/reports/reports.component.html, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html, modules/ui/src/app/pages/testrun/testrun.component.html, modules/ui/src/app/services/focus-manager.service.spec.ts, modules/ui/src/app/services/focus-manager.service.ts
Focus title or first element in container when navigation is triggered by enter
Tests
http://screencast/cast/NjYzMDg4ODY4NjIyMzM2MHw0ZTkzZWRkZC05ZA
=> The focus is not moved to the page headline on opening the page using the keyboard

modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.ts
=> Adds aria label and tooltip to risk profile icons

modules/ui/src/app/model/profile.ts, modules/ui/src/app/pages/devices/components/device-form/device.validators.ts, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.spec.ts, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Tests
http://screencast/cast/NjM0ODAxMzU1MDE3NDIwOHxlZDZlZWUwNi0yMA
=> Adds copy of risk profile

modules/ui/src/styles.scss
Ticket: 351758698
fix: update app version styles to meet design on expanded nav
https://screenshot.googleplex.com/4tr8TiTvnvntNWW
https://screenshot.googleplex.com/C8ER35n5gc976BX
=> 351758698: (fix) update app version styles to meet design on expanded nav

modules/ui/src/app/store/effects.spec.ts, modules/ui/src/app/store/effects.ts
=> Fix step 1 callout error

modules/ui/src/app/app.component.ts, modules/ui/src/app/app.store.spec.ts, modules/ui/src/app/app.store.ts, modules/ui/src/app/mocks/device.mock.ts, modules/ui/src/app/pages/devices/devices.component.html, modules/ui/src/app/pages/devices/devices.component.spec.ts, modules/ui/src/app/pages/devices/devices.component.ts, modules/ui/src/app/pages/devices/devices.store.spec.ts, modules/ui/src/app/pages/devices/devices.store.ts, modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.spec.ts, modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.ts, modules/ui/src/app/pages/testrun/testrun.component.html, modules/ui/src/app/pages/testrun/testrun.component.spec.ts, modules/ui/src/app/pages/testrun/testrun.component.ts, modules/ui/src/app/pages/testrun/testrun.store.spec.ts, modules/ui/src/app/pages/testrun/testrun.store.ts, modules/ui/src/app/services/test-run.service.spec.ts, modules/ui/src/app/services/test-run.service.ts, modules/ui/src/app/store/actions.ts, modules/ui/src/app/store/reducers.spec.ts, modules/ui/src/app/store/reducers.ts, modules/ui/src/app/store/selectors.spec.ts, modules/ui/src/app/store/selectors.ts, modules/ui/src/app/store/state.ts
Tests
https://screencast.googleplex.com/cast/NjA3NzAyNjg4MzYwMDM4NHxmMDc5MDc2ZC01Mg
=> Load test modules dynamically

modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html, modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.scss, modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.spec.ts, modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.ts, modules/ui/src/app/pages/testrun/testrun.component.html
Update download zip modal: add link to Risk Profiles, remove redirect button, rename download button, add No Profile option
Valid profiles available
No valid profiles available
Tests
=> Update download Zip file modal

modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html
Ticket: 347009372
feat: add selector for profile options for track GA4 for download zip with profile
=> 347009372: (feat) add selector for profile options for GA4

modules/ui/angular.json, modules/ui/package-lock.json, modules/ui/package.json, modules/ui/src/app/app.component.spec.ts, modules/ui/src/app/app.component.ts, modules/ui/src/app/app.module.ts, modules/ui/src/app/app.store.spec.ts, modules/ui/src/app/app.store.ts, modules/ui/src/app/mocks/settings.mock.ts, modules/ui/src/app/model/setting.ts, modules/ui/src/app/model/topic.ts, modules/ui/src/app/pages/settings/settings.store.spec.ts, modules/ui/src/app/pages/settings/settings.store.ts, modules/ui/src/app/services/test-run-mqtt.service.spec.ts, modules/ui/src/app/services/test-run-mqtt.service.ts, modules/ui/src/app/store/actions.ts, modules/ui/src/app/store/reducers.spec.ts, modules/ui/src/app/store/reducers.ts, modules/ui/src/app/store/selectors.spec.ts, modules/ui/src/app/store/selectors.ts, modules/ui/src/app/store/state.ts
Adds mqtt client, adds pop up when new adapter is available
Tests
Videos after changes
https://screencast.googleplex.com/cast/NTExNDAxMTY5ODg1NTkzNnwyNDE5YTNmMi0yYg
https://screencast.googleplex.com/cast/NjY3Mjc1NjE2MTY0MjQ5NnwwMWNlMzI1NS1lNA
https://screencast.googleplex.com/cast/NDg1NDM1OTgyMDA3NTAwOHw2OTQ5MGNlZS05Yw
=> Inform about a new network adapter

modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Tests
http://screencast/cast/NjE1NDQ5MzI5NjExNTcxMnxjNmVhNGZmNC1iOA
http://screencast/cast/NDY0MDA1NjI1MjgyNTYwMHxlMDkwMjVmMC01OA
=> If profile is editing, return focus on profile

modules/ui/src/app/mocks/profile.mock.ts, modules/ui/src/app/model/profile.ts, modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html, modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.scss, modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts, modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.html, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts, modules/ui/src/app/services/test-run.service.ts
Adds styles for expired profile; disable all fields when profile is expired; regenerate form with profile questions
Tests
Screenshots after changes
=> Expired profile profile

modules/ui/src/app/app.component.html, modules/ui/src/app/app.component.spec.ts
=> Adds tooltip

modules/ui/src/app/app.component.html, modules/ui/src/app/app.component.scss, modules/ui/src/app/app.component.spec.ts, modules/ui/src/app/app.component.ts, modules/ui/src/app/app.module.ts, modules/ui/src/app/app.store.spec.ts, modules/ui/src/app/app.store.ts, modules/ui/src/app/components/wifi/wifi.component.html, modules/ui/src/app/components/wifi/wifi.component.scss, modules/ui/src/app/components/wifi/wifi.component.spec.ts, modules/ui/src/app/components/wifi/wifi.component.ts, modules/ui/src/app/mocks/topic.mock.ts, modules/ui/src/app/model/topic.ts, modules/ui/src/app/services/test-run-mqtt.service.spec.ts, modules/ui/src/app/services/test-run-mqtt.service.ts
http://screencast/cast/NTc5MDA1MzgxMTg3OTkzNnw3NmQ2ZGMxMS01MA
Tests
=> Adds internet icon

modules/ui/src/app/model/testrun-status.ts, modules/ui/src/app/services/test-run.service.spec.ts, modules/ui/src/app/services/test-run.service.ts
=> Adds test statuses

modules/ui/src/app/interceptors/error.interceptor.spec.ts, modules/ui/src/app/interceptors/error.interceptor.ts
=> Show error message if provided; show default message if no

modules/ui/src/app/components/stepper/stepper.component.html, modules/ui/src/app/components/stepper/stepper.component.scss, modules/ui/src/app/components/stepper/stepper.component.ts, modules/ui/src/app/pages/devices/components/device-form/device-form.component.spec.ts, modules/ui/src/app/pages/devices/components/device-form/device-form.component.ts, modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html, modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss, modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.spec.ts, modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts, modules/ui/src/app/pages/devices/devices.component.html, modules/ui/src/app/pages/devices/devices.component.spec.ts, modules/ui/src/app/pages/devices/devices.component.ts
Adds summary step; add close form pop-up; save is not in scope
Tests
http://screencast/cast/NTAwMjM0ODUyMTg0ODgzMnw2ZjkyY2NlZS1kNQ
=> Device profile summary

modules/ui/src/app/components/callout/callout.component.html
=> Only closeable banner should have close button

modules/ui/src/app/components/device-item/device-item.component.html, modules/ui/src/app/components/device-item/device-item.component.scss, modules/ui/src/app/components/device-item/device-item.component.spec.ts, modules/ui/src/app/components/device-item/device-item.component.ts, modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.html, modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.ts, modules/ui/src/app/pages/testrun/testrun.component.html, modules/ui/src/app/pages/testrun/testrun.component.spec.ts, modules/ui/src/app/pages/testrun/testrun.store.spec.ts, modules/ui/src/app/pages/testrun/testrun.store.ts, modules/ui/src/app/store/actions.ts, modules/ui/src/app/store/effects.spec.ts, modules/ui/src/app/store/effects.ts, modules/ui/src/app/store/reducers.spec.ts, modules/ui/src/app/store/reducers.ts, modules/ui/src/app/store/selectors.spec.ts, modules/ui/src/app/store/selectors.ts, modules/ui/src/app/store/state.ts, modules/ui/src/theming/colors.scss
Ticket: 360106064
feat: display outdated device profiles
https://screencast.googleplex.com/cast/NTU5MzE5MDg2NTMwNTYwMHw3ZGJkOTY3Zi1hNg
https://screenshot.googleplex.com/APFhWMoqXZZnhdk
https://screenshot.googleplex.com/AV6QFiWw8829eQt
=> 360106064: (feat) display outdated device profiles

modules/ui/src/app/components/stepper/stepper.component.html, modules/ui/src/app/components/stepper/stepper.component.ts, modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
Change aria-label and tooltip for stepper
=> Aria labels for stepper and Go to next step button are incorrect

modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.spec.ts, modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
Close form without confirmation if no changes were made
http://screencast/cast/NTQ0NTkxMTg3MzMyMzAwOHw3ZjJlMzQ2MC1mNg
Tests
=> Confirmation of closing is displayed when no changes made in Device menu

modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
=> Fix overflow; fix hint on small form width

modules/ui/src/styles.scss
Ticket: 362470780
fix: change for preventing callouts overlapping
https://screenshot.googleplex.com/QW2u2ueuPUthrYn
https://screenshot.googleplex.com/5vhUgB9g9aWfBaQ
=> 362470780: (fix) change for preventing callouts overlapping

modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss, modules/ui/src/styles.scss, modules/ui/src/theming/variables.scss
Ticket: 362921863
fix: create device popup view in Firefox
https://screenshot.googleplex.com/6mupgzcctdn4pwP
https://screencast.googleplex.com/cast/NDg3MDEyNzk1MzY0MTQ3MnxjM2I4ZWZhZS02OA
=> 362921863: (fix) create device popup view in firefox

modules/ui/src/app/components/callout/callout.component.html, modules/ui/src/app/components/callout/callout.component.scss
Ticket: 362924178
fix: change to align information on the welcome modal
https://screenshot.googleplex.com/AHaYE8U9UUy2hiP
https://screenshot.googleplex.com/4zSCS2xWvbg3RYK
=> 362924178: (fix) change to align information on the welcome modal

modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
Before
http://screencast/cast/NjQ1NzQ2NjA5NDA5MjI4OHxhNDBlNmZhNy0yNQ
After
http://screencast/cast/NjAyNTU1NjI5NzUxNTAwOHxlNDk1ZGRlMS1lZg
=> Check is value is null, undefined or empty string

modules/ui/src/app/app.component.html, modules/ui/src/app/components/callout/callout.component.html, modules/ui/src/app/components/callout/callout.component.scss, modules/ui/src/app/components/callout/callout.component.ts, modules/ui/src/styles.scss
Ticket: 364545807
fix: changes to prevent the second callout is hidden
https://screencast.googleplex.com/cast/NTY0Mzk0NTgzNjAxOTcxMnw4ZjAzYjA3ZC03Mg
=> 364545807: (fix) changes to prevent the second callout is hidden

modules/ui/src/app/components/device-item/device-item.component.scss
Ticket: 364578734: 
fix: change device tile view to meet size
https://screenshot.googleplex.com/7SdE5YRL8GpcmDQ
https://screenshot.googleplex.com/9XGQMKxDLLM28XM
=> 364578734: (fix) change device tile view to meet size

modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
Change button type to have the same background color
=> Delete and Cancel buttons have different background colors on hover

modules/ui/src/app/app.module.ts, modules/ui/src/app/components/callout/callout.component.scss, modules/ui/src/app/store/effects.ts
Fix host name; fix status update; fix css property typo
https://screencast.googleplex.com/cast/NTc3Njg5OTkwNDExMDU5Mnw5N2Q5MjhjYi04Yg
=> No update from BE of test status results during testrun

modules/ui/src/app/app.component.ts
Focus first interactive element on redirect to risk assessment
http://screencast/cast/NTIwNjIzNzM5NzM4NTIxNnwyZDg1YTZiMS04Mg
=> The focus is not set to the first interactive element after clicking the "Risk assessment questionnaire"link on the callout

framework/python/src/test_orc/test_orchestrator.py, resources/test_packs/qualification.json
- Add dhcp disconnect tests to qual test pack
- Add test descriptions to test results
=> misc bug fixes

modules/ui/src/app/pages/devices/devices.component.ts
Filter devices to open device dialog if all devices are outdated
Video after chages
http://screencast/cast/NDc0NzQ0MjQ4MTI2NjY4OHxmYTJhNmQ2OS00Nw
=> The link in the collout Step 2 doesn't work if the outdated devices are available

modules/ui/src/app/pages/reports/reports.component.html
Rename column "Program" to "Assessment type"
=> Rename Program column on Reports tab

modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html, modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.spec.ts
=> Hide "Create" text in edit mode

modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html, modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
Prevent default event
Before
http://screencast/cast/NDk1MzM0MjM0MTAyMTY5Nnw3NDg0YzlmZC1iYQ
After
http://screencast/cast/NDUxMzc1NDc4NzA4NjMzNnw4ZTZmNjI4Mi03OA
=> The link to validation error on the final summary device page opens the Cancel dialog

modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.html, modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.spec.ts, modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Show success dialog only for valid risk profile
https://screencast.googleplex.com/cast/NjE5MjgzNDYwMzM4NDgzMnxjZWIzYmRiOS0yYw
https://screencast.googleplex.com/cast/NDY4NzUyMzIyNDc0ODAzMnw4YWQzNmEyYy1kZg
https://screencast.googleplex.com/cast/NTg0NTM5MDc0MDk0Njk0NHwxMjY4MTI2MS1iYQ
=> Update Risk profile result modal logic

modules/ui/package-lock.json, modules/ui/src/app/components/version/version.component.html, modules/ui/src/app/components/version/version.component.spec.ts, modules/ui/src/app/components/version/version.component.ts
=> Change version label

modules/ui/src/app/store/effects.ts
Before
http://screencast/cast/NDY4OTk2NTMxNjMwODk5MnxjZmQ1OGNmNi02Yg
After
http://screencast/cast/NTg5MzI5NDg5MzU2MzkwNHw2ZGI5YzI2Mi1lNQ
=> Destroy "waiting for device" snackbar when status changed

modules/ui/src/app/components/dynamic-form/dynamic-form.component.ts
Mark dirty only multi select control when tab navigation
Before
http://screencast/cast/NjU4NTE1MzQ5MjA5MDg4MHwyZWE2MjcxMy00Nw
After
http://screencast/cast/NTI4MzQ5MDYzODU5NDA0OHxkOTUzOGFiMi0zMw
=> The focus on the specific answer in the risk profile is counted as updating data and activates the Discard button

modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts, modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts, modules/ui/src/app/components/testing-complete/testing-complete.component.ts
Adds focus flow after closing download zip/testing complete dialog
Tests
http://screencast/cast/NjI3NjY5MjIyOTIyNjQ5NnwxZDJjMTdjNi1lYg
=> The focus is not visible after the Complete testing modal is closed.

modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
Adds timeout to allow screen reader to detect changes and pronounce the changes on page
=> New Risk Assessment button is not announced after removing all Risk Profiles

modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.store.spec.ts
=> Focus moves out of Risk Profile form when tab cycling

modules/ui/src/app/components/testing-complete/testing-complete.component.ts
Ticket: 369106935
fix: [a11y] make focused element announced
https://screencast.googleplex.com/cast/NDU5NjcwNDc2NTU0MjQwMHxlNzI4MzUyYS1hOQ
=> 369106935: (fix) [a11y] make focused element announced

modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Focus with delay to allow screen reader detect changes
=> The focused risk profile is not communicated by screen reader after saving it on the list 

modules/ui/src/app/app.component.html, modules/ui/src/app/app.component.ts
Focus risk assessment link when appears
http://screencast/cast/NDc0NjE2Mzc4ODk3MjAzMnwxMjUxMzEzOC0wNg
=> The focus is not moved to the callout about risk profile questionnaire while running the test attempt 

modules/ui/src/app/app.component.spec.ts, modules/ui/src/app/app.component.ts
Ticket: 369314564
fix: set focus after callout dismissed
https://screencast.googleplex.com/cast/NjIyNzI5ODE1OTE2NTQ0MHw3MzhhNTQ0OS00OQ
=> 369314564: (fix) set focus after callout dismissed

modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.spec.ts, modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.ts
Ticket: 369312866
fix: set focus after welcome modal is closed
https://screencast.googleplex.com/cast/NjQwMjE3NTUzNzI1MDMwNHxjYjliZWE2Ny0wZQ
=> 369312866: (fix) set focus after welcome modal is closed

modules/ui/src/styles.scss
http://screencast/cast/NTgxMzQzODE2Mzk3NjE5Mnw5NmZiODYyNS0yZg
=> Fix profiles page style to fit the screen

modules/ui/src/app/model/setting.ts, modules/ui/src/app/store/effects.ts
Ticket: 358071738
feat: prevent listening mgtt internet connect event in single port mode
=> 358071738: (feat) prevent listening mgtt internet connect event in single port mode

modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
http://screencast/cast/NjQwNTkwMTk1ODI1MDQ5NnxhNzA1ZmU5YS1kMg
=> Fix condition to show dialog on name change

modules/ui/src/app/pages/testrun/testrun.component.ts
Ticket: 369538601
fix: set focus to first interactive elem after stop test attempt
https://screencast.googleplex.com/cast/NTIyMjk2MjIwMTM2MjQzMnxmYjNlYzk4OC1iZA
=> 369538601: (fix) set focus to first interactive elem after stop test attempt

modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Ticket: 369327155
fix: set focus to selected risk profile if no changes on edit
https://screencast.googleplex.com/cast/NjQ4Nzk4ODU0NzYxNjc2OHwyOWFmYjJiOS1iMA
https://screencast.googleplex.com/cast/NjEwNDk3NzQ5MDU3NTM2MHwzYTk2NDEzNi1mNQ
=> 369327155: (fix) set focus to selected risk profile if no changes on edit

modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.html
Active delete button on space and enter
=> Delete icon is implemented as a link and does not react to Space button

modules/ui/src/app/components/dynamic-form/dynamic-form.component.html
Ticket: 369779748
fix: add field name to validation rule for announce by Screen Reader
https://screencast.googleplex.com/cast/NjQxODM0MDE4MzUzOTcxMnxlNDhjZDVlNy0yNQ
=> 369779748: (fix) add field name to validation rule for announce by Screen Reader

modules/ui/src/app/pages/devices/devices.component.spec.ts, modules/ui/src/app/pages/devices/devices.component.ts, modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.spec.ts, modules/ui/src/app/pages/testrun/components/testrun-initiate-form/testrun-initiate-form.component.ts
Add delay and fix dialog open configuration
=> Firmware is not entered in testrun dialog after navigation to it with screen reader ON

modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html
Ticket: 367979183
fix: apply role "status" to announce the result and description on completed test modal 
https://screencast.googleplex.com/cast/NDk4OTAwNTQ2Nzc0NjMwNHw5NWE4MjJkMS1kOQ
=> 367979183: (fix) announce the result and description on completed test modal

modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html, modules/ui/src/app/components/testing-complete/testing-complete.component.spec.ts, modules/ui/src/app/components/testing-complete/testing-complete.component.ts
Ticket: 369542969
fix: announce completed test modal
https://screencast.googleplex.com/cast/NjI2MjY5MDk3MTM4NTg1NnxhNTRlN2JlNy0wYw
=> 369542969: (fix) announce completed test modal

framework/python/src/common/session.py
- updated '_load_version' method from session module to correctly retrieve the version from make control file 
- added error handling if the version line is missing from control file
=> Fix '_load_version' from session module

modules/ui/src/app/pages/testrun/testrun.component.spec.ts, modules/ui/src/app/pages/testrun/testrun.component.ts, modules/ui/src/app/services/notification.service.ts
Ticket: 369538601
fix: focus first interactive elem on start or stop testrun
https://screencast.googleplex.com/cast/NDY2NDM2NDMyNDg4MDM4NHw1NzVjY2VjYy0wMg
https://screencast.googleplex.com/cast/NjAwNTc1MDcyNjkxODE0NHxlZjJjMDEwYy01ZA
=> 369538601: (fix) focus first interactive elem on start or stop testrun

modules/ui/src/app/components/testing-complete/testing-complete.component.ts, modules/ui/src/app/guards/can-deactivate.guard.spec.ts, modules/ui/src/app/guards/can-deactivate.guard.ts, modules/ui/src/app/pages/devices/devices.component.spec.ts, modules/ui/src/app/pages/devices/devices.component.ts
Adds deactivate guard for devices page
http://screencast/cast/NjU3NjE4NzQ3OTQyNTAyNHwzMDNhYWI2Yi1iYQ
=> The user is not navigated to the Device popup on clicking the Cancel on the confirmation dialog

modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
Ticket: 369788198
fix: validation message alignment on create device
https://screenshot.googleplex.com/4E547KBCmZ6s4ox
https://screenshot.googleplex.com/77WrvK6i8cStC9q
=> 369788198: (fix) validation message alignment on create device

modules/ui/src/app/components/dynamic-form/dynamic-form.component.html, modules/ui/src/app/components/dynamic-form/dynamic-form.component.spec.ts
Ticket: 370729271
fix: remove asterisks on the questions in the device flow
https://screenshot.googleplex.com/8ZjHCmArqyv9xZ9
https://screenshot.googleplex.com/8rTuyP4F4qUorYk
=> 370729271: (fix) remove asterisks on the questions in the device flow

modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html
Add role and aria-live for screen reader
http://screencast/cast/NTAyMjU1MzcyNTczMDgxNnxjYjQwNzkzZi05OQ
=> Add role and aria-live for screen reader

modules/ui/src/app/pages/certificates/certificates.component.html, modules/ui/src/app/pages/certificates/certificates.component.spec.ts, modules/ui/src/app/pages/certificates/certificates.component.ts
Ticket: 370923173
fix: remove close button from the certificates panel
https://screenshot.googleplex.com/9uhMNSJNBuCy7z5
=> 370923173: (fix) remove close button from the certificates panel

modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.html, modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.spec.ts, modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.ts
=> Change text in risk dialog

modules/ui/src/app/components/version/version.component.spec.ts, modules/ui/src/app/components/version/version.component.ts
Ticket: 371506031
fix: make the welcome modal be on top completed test modal
https://screencast.googleplex.com/cast/NTY1MTM3MTI5NzYwMzU4NHxlNzEwMTQyYy0xMw
https://screencast.googleplex.com/cast/NjIxNDMyMTI1MTAyNDg5NnwyMDk3ZDYwYi0yYw
=> 371506031: (fix) make the welcome modal be on top completed test modal

modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts, modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts
Ticket: 370941517
fix: return focus to initial button after cancel download zip
https://screencast.googleplex.com/cast/NjY4MDIzMTM2NzY3MTgwOHw0NGY5MDNiZS0zYQ
https://screencast.googleplex.com/cast/NTQ1MTgxNjA0NDA2ODg2NHw5MzYzMWI0OS02YQ
=> 370941517: (fix) return focus to initial btn after cancel download zip

modules/ui/src/app/mocks/testrun.mock.ts, modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.spec.ts, modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.ts
Ticket: 371525395
fix: exclude error status from count of completed test result
https://screenshot.googleplex.com/645d8htWckkcGGh
https://screenshot.googleplex.com/7S5Wd4LozUK4Q8e
=> 371525395: (fix) exclude error status from count of completed test result

modules/ui/src/app/pages/devices/devices.component.spec.ts, modules/ui/src/app/pages/devices/devices.component.ts
Ticket: 371948760
fix: set focus to first interactive elem after start testrun from device
https://screencast.googleplex.com/cast/NjU1NTA1ODE4NjQ4NTc2MHxlYmFlMTk0Zi1mMQ
https://screencast.googleplex.com/cast/NTEwMjAyNDUxMjI0MTY2NHw5YjczYTk4Ni1lYg
=> 371948760: (fix) set focus to first interactive elem after start testrun from device

modules/test/dns/python/src/dns_module.py, modules/test/ntp/python/src/ntp_module.py, modules/test/services/python/src/services_module.py, resources/report/header_macros.jinja, resources/report/test_report_styles.css, resources/report/test_report_template.html, testing/unit/dns/reports/dns_report_local.html, testing/unit/dns/reports/dns_report_local_no_dns.html, testing/unit/ntp/reports/ntp_report_local.html, testing/unit/ntp/reports/ntp_report_local_no_ntp.html, testing/unit/services/reports/services_report_all_closed_local.html, testing/unit/services/reports/services_report_local.html
Before:
[report_example.pdf](https://github.com/user-attachments/files/17298934/report_example.pdf)
After:
[report.pdf](https://github.com/user-attachments/files/17299442/report.pdf)
=> Fix navigation structure in PDF report

framework/python/src/common/testreport.py, resources/report/test_report_template.html
[report.pdf](https://github.com/user-attachments/files/17307420/report.pdf)
=> pdf report duration format

modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.html, modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.spec.ts, modules/ui/src/app/pages/risk-assessment/components/success-dialog/success-dialog.component.ts
Ticket: 372610099
fix: [Demo feedback] update the text for Risk assessment complete modal
https://screenshot.googleplex.com/9mHVH9cU4A7PFUd
https://screenshot.googleplex.com/9xGHeApSmtvB6cB
=> 372610099: (fix) update the text for Risk assessment complete modal

modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts, modules/ui/src/app/components/download-report-zip/download-report-zip.component.ts, modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.spec.ts, modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.ts, modules/ui/src/app/components/testing-complete/testing-complete.component.spec.ts, modules/ui/src/app/components/testing-complete/testing-complete.component.ts
Adds action value instead of null, undefined, string; move common functionality in component
=> Modify download zip modal

modules/ui/src/app/components/download-report/download-report.component.spec.ts, modules/ui/src/app/components/report-action/report-action.component.spec.ts, modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.spec.ts, modules/ui/src/app/pages/reports/components/filter-chips/filter-chips.component.spec.ts, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.spec.ts, modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.spec.ts, modules/ui/src/app/services/notification.service.spec.ts
Ticket: 369806347
Improve unit tests
https://screenshot.googleplex.com/BqCLCEzNaZXsgB4
https://screenshot.googleplex.com/9oFesk3FRxwqHzo
https://screenshot.googleplex.com/t7RsDkaWsMYFxvP
https://screenshot.googleplex.com/3sjuq7p3mKLkALK
=> 369806347: (fix) improve unit tests

modules/ui/src/app/app.store.spec.ts, modules/ui/src/app/app.store.ts
Send event to GA when test run is completed for Pilot program
=> [GA4] Track Pilot assessment results

modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss
Ticket: 373617780
fix: change to allow MAC address error text move on to next line
https://screenshot.googleplex.com/DuuMyJvHMzFAhyf
https://screenshot.googleplex.com/7i8MsZU2d8Q7xs9
=> 373617780: (fix) change to allow MAC address error text move on to next line

modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts
Ticket: 373855404
fix: allow to change case of letters for existing profile name
https://screencast.googleplex.com/cast/NjUzMjUxNjY1NDYxMjQ4MHw3MzZlNjA3MS1lOQ
=> 373855404: (fix) allow to change case of letters for existing profile name

modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html, modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.spec.ts
Change error message
Before
http://screencast/cast/NTM2MTAzOTI3NjI0NDk5MnwxMWI3OThjOS1hYg
After
http://screencast/cast/NjY3ODM3ODQ5MTkzNjc2OHw5NjdkNDBmMy02ZQ
=> Uniqueness error is not read by screen reader if navigate fields with Tab

modules/ui/src/app/components/testing-complete/testing-complete.component.ts, modules/ui/src/app/store/effects.spec.ts, modules/ui/src/app/store/effects.ts
Hide complete dialog if test run is missing in reports
Before
http://screencast/cast/NjQ5MjYyODQ4ODAyODE2MHwyNjY5YjRmNi02MA
After
http://screencast/cast/NDgzMTg2NTA3OTg1NzE1MnxmNWE1YTg2NS1hMg
=> The Complete testing modal is shown with Idle result if the app is reopened in another tab

modules/ui/src/app/app.store.spec.ts, modules/ui/src/app/app.store.ts
Skip first default values to display error correctly
Before
http://screencast/cast/NTc2MTc4NzM3MzgxMzc2MHxmNjY1ZGQ1OC02Nw
After
http://screencast/cast/NjYwNTkyMjY2MjA4ODcwNHxkMTM5OGRjZS1jYg
=> The "No ports" callout blinks on loading the page 

modules/ui/src/app/components/dynamic-form/dynamic-form.component.html, modules/ui/src/app/components/dynamic-form/dynamic-form.component.ts, modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts
Adds separate method for value
http://screencast/cast/NTEzNDQ3MDE3MTU5MDY1NnxhNzBlZTkwZC1iOA
=> The answers to questions in the Device popup are not displayed

modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.spec.ts, modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.ts
Change test in Delete Report Dialog
=> The text in the Delete Report dialog is not consistent with other typical dialogs

modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.scss
=> The font for Non- Compliant results is not by design

modules/ui/src/app/pages/settings/settings.component.ts
Fix is based on console error (see screenshot)
=> The Testing complete popup is shown incorrectly

modules/ui/src/app/pages/reports/reports.component.html, modules/ui/src/app/pages/reports/reports.component.scss, modules/ui/src/index.html, modules/ui/src/styles.scss, modules/ui/src/theming/m3-theme.scss, modules/ui/src/theming/variables.scss
=> Apply new styles for reports table

modules/ui/src/app/components/download-report/download-report.component.html, modules/ui/src/app/components/download-report/download-report.component.scss, modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.html, modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.scss, modules/ui/src/app/pages/reports/reports.component.scss, modules/ui/src/theming/mixins.scss
Fix lighthouse aria label issue
Adds hover styles
http://screencast/cast/NTcxODU1Njc4MzE0OTA1Nnw5Mzc3MTJkMi0xYw
=> Adds aria-label and hover styles

modules/ui/src/app/app.component.html, modules/ui/src/styles.scss
Ticket: 379246727
fix: change certificate button to filled view
https://screenshot.googleplex.com/9QvAszD8oPoJ9He
=> 379246727: (fix) change certificate button to filled view

modules/ui/src/app/app.component.scss
http://screencast/cast/NjAxNzY5NjE1NTA0MTc5MnxjZDIyNGQzZS05NA
=> Adds style for focused logo

modules/ui/src/app/pages/reports/reports.component.scss, modules/ui/src/theming/mixins.scss
=> Adds style for better spacing between elements

modules/ui/src/app/app.component.html, modules/ui/src/app/app.component.scss
Before
https://screencast.googleplex.com/cast/NjIzNTQ0NDg5MDA0MjM2OHwxZWNiMDg1NC0zZg
After
http://screencast/cast/NDU3MjcyOTUxOTg5ODYyNHw2YjdjNTZhZC1mZA
=> Header: Logo and app name serve as a main button

make/DEBIAN/control, modules/ui/src/app/components/download-report-zip/download-report-zip.component.spec.ts
Added version 2.1 to control file
Fixed ESlint
=> Added version 2.1

modules/ui/src/app/pages/reports/components/filter-chips/filter-chips.component.scss, modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.scss
Ticket: 382457675
fix: changes for calendar filter issues
https://screencast.googleplex.com/cast/NjYxNzk2Nzk4MTc1NjQxNnw5MmU4ZTQwZC0yZg
=> 382457675: (fix) changes for calendar filter issues

modules/ui/src/app/pages/reports/components/filter-header/filter-header.component.html, modules/ui/src/app/pages/reports/components/filter-header/filter-header.component.scss, modules/ui/src/app/pages/reports/components/filter-header/filter-header.component.spec.ts, modules/ui/src/app/pages/reports/components/filter-header/filter-header.component.ts, modules/ui/src/app/pages/reports/reports.component.html, modules/ui/src/app/pages/reports/reports.component.scss, modules/ui/src/styles.scss, modules/ui/src/theming/variables.scss
Fixed issues:
+ Buttons order
+ Focus border
+ Sorting button color
+ Default sorting indicator
=> The sorting icon and column name defect on focused state

modules/ui/src/app/model/filters.ts, modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.html, modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.scss, modules/ui/src/styles.scss
Ticket: 382461850
fix: changes for result filter
https://screencast.googleplex.com/cast/NTQ0NDI5ODM1ODEyODY0MHw4MDBlNzNmYy1mNw
=> 382461850: (fix) changes for result filter

modules/ui/src/app/components/snack-bar/snack-bar.component.scss, modules/ui/src/main.ts, modules/ui/src/styles.scss, modules/ui/src/theming/colors.scss, modules/ui/src/theming/m3-theme.scss
=> Adds styles for snackbar

modules/ui/src/app/pages/general-settings/general-settings.component.html, modules/ui/src/app/pages/general-settings/general-settings.component.spec.ts
Ticket: 380231252
fix: save button becomes active when any setting changes
https://screencast.googleplex.com/cast/NDg3OTUwMTE2NjExNjg2NHw2MTdkMmIzZS01OA
=> 380231252: (fix) save button becomes active when any setting changes

modules/ui/src/app/pages/general-settings/general-settings.component.spec.ts, modules/ui/src/app/pages/general-settings/general-settings.component.ts, modules/ui/src/app/pages/general-settings/general-settings.store.ts
Ticket: 386919467
fix: make internet port disable in single mode after enable form
https://screencast.googleplex.com/cast/NDYxMDgyMDQ5NDMyNzgwOHxiOGMzZDI5OC0zZQ
=> 386919467: (fix) make internet port disable in single mode after enable form

modules/ui/src/app/pages/general-settings/general-settings.component.scss, modules/ui/src/styles.scss, modules/ui/src/theming/variables.scss
Ticket: 387242682
fix: make save button available on the settings page with callouts
https://screencast.googleplex.com/cast/NjM2NzY5NjAyNjMzNzI4MHw0YmVjOTY2Yi03OA
=> 387242682: (fix) make save button available on the settings page with callouts

modules/ui/src/app/components/list-layout/list-layout.component.scss
Ticket: 387461943: 
fix: remove double scroll on device page
https://screencast.googleplex.com/cast/NTA1MDMwOTU2NjAwNTI0OHxiMTU0MDA2Mi0xNA
https://screencast.googleplex.com/cast/NjQ3ODI0NDcyNjQzOTkzNnw3ZTU5NzQ2ZC0xMA
=> 387461943: (fix) remove double scroll on device page

modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html, modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss, modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.spec.ts, modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts, modules/ui/src/app/pages/devices/devices.component.html, modules/ui/src/app/pages/devices/devices.component.scss, modules/ui/src/app/pages/devices/devices.component.spec.ts, modules/ui/src/app/pages/devices/devices.component.ts, modules/ui/src/app/pages/devices/devices.store.ts
https://screencast.googleplex.com/cast/NTgxOTc3ODQ5MjAwNjQwMHxkNDM4ODA2NS01OQ
+ change dialog width
=> Saving modal

modules/ui/src/app/components/list-layout/list-layout.component.ts, modules/ui/src/app/model/layout-type.ts, modules/ui/src/app/pages/devices/devices.component.html, modules/ui/src/app/pages/devices/devices.component.ts
Ticket: 385169778
feat: apply search for devices
https://screencast.googleplex.com/cast/NjU1NTM3NDU1NDQ0Nzg3MnxlMzhiMGJiZi1lOQ
=> 385169778: (feat) apply search for devices

modules/ui/src/app/components/device-item/device-item.component.scss, modules/ui/src/app/components/list-item/list-item.component.html, modules/ui/src/app/components/list-item/list-item.component.scss, modules/ui/src/app/components/list-item/list-item.component.spec.ts, modules/ui/src/app/components/list-item/list-item.component.ts, modules/ui/src/app/components/list-layout/list-layout.component.html, modules/ui/src/app/components/list-layout/list-layout.component.scss, modules/ui/src/app/components/list-layout/list-layout.component.ts, modules/ui/src/app/pages/devices/devices.component.html, modules/ui/src/app/pages/devices/devices.component.scss, modules/ui/src/app/pages/devices/devices.component.ts
Adds title for device under test; fix background for Outdated device
http://screencast/cast/NTc5NTY2MjQ4NTUyMDM4NHw4YjNlZjMyNS01OA
=> Device under test hint & color of the outdated device 

modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss, modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.spec.ts, modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts, modules/ui/src/app/pages/devices/devices.component.scss, modules/ui/src/app/pages/devices/devices.component.ts
Fix dialog width
Video after chages
http://screencast/cast/NjU5OTQzNTQxNTk3Nzk4NHxmMzgwNTEwNi0zZQ
=> Corrupted welcoming modal

modules/ui/src/app/pages/devices/devices.component.ts
Ticket: 392037156
fix: [GM3] close form after delete device
https://screencast.googleplex.com/cast/NjEyOTA5MDI5MjYxMzEyMHw5ZTA0Y2YxOS0zOA
https://screencast.googleplex.com/cast/NTQ1MTg1NTc4OTI5MzU2OHxjYjdjYjNiMy01OQ
=> 392037156: (fix) [GM3] close form after delete device

modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.html, modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.scss, modules/ui/src/index.html, resources/report/test_report_styles.css, resources/report/test_report_template.html
=> Adds column order in testing table; adds missing icons for statuses

modules/ui/src/app/components/list-layout/list-layout.component.html, modules/ui/src/app/components/list-layout/list-layout.component.scss, modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.ts, modules/ui/src/app/pages/devices/devices.component.html, modules/ui/src/app/pages/devices/devices.component.ts
http://screencast/cast/NTc2NTMwOTIxMzQ0MjA0OHxiNmM3ZDUyZC05Ng
=> Devices: The <Create New Device> to be disabled upon creating new device

modules/ui/src/app/app.store.spec.ts, modules/ui/src/app/app.store.ts, modules/ui/src/app/components/download-report/download-report.component.ts, modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.html, modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.ts, modules/ui/src/app/mocks/reports.mock.ts, modules/ui/src/app/mocks/testrun.mock.ts, modules/ui/src/app/model/testrun-status.ts, modules/ui/src/app/pages/testrun/components/download-options/download-options.component.ts, modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.html, modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.scss, modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.spec.ts, modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.ts, modules/ui/src/app/services/test-run.service.spec.ts, modules/ui/src/app/store/effects.ts
Adds pilot recommendation to status card
Device qualification
Pilot assessment
=> Add information to Results box (Testing tab)

modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.html
=> Fix text in test run status card

modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.html
Show pilot recommendations only for Proceed and Do not proceed statuses
=> [2.1.1 Release ] Pilot recommendation <Cancelled>

framework/python/src/common/testreport.py
=> Remove steps_to_resolve logs

modules/ui/src/app/components/device-item/device-item.component.scss, modules/ui/src/app/pages/risk-assessment/profile-item/profile-item.component.scss
Ticket: 396366298
fix: [GM3] prevent corrupting profile if it has long name
- Profiles:
https://screenshot.googleplex.com/BpCQUs66NGzMkgo
- Devices:
https://screenshot.googleplex.com/7fDz9TXaEA3BpAQ
- Profiles:
https://screenshot.googleplex.com/y85BHQd6JK7dX5n
- Devices:
https://screenshot.googleplex.com/5nqttUXpAFbRSeo
=> 396366298: (fix) [GM3] prevent corrupting profile if it has long name

modules/ui/src/theming/mixins.scss
Ticket: 395677144
fix: [GM3] A11Y: move button on the next line to prevent corrupting sticky menu
https://screenshot.googleplex.com/9V3YUuJakpRpaYU
https://screenshot.googleplex.com/5wV8wuZoAt8SpwQ
=> 395677144: (fix) [GM3] A11Y: move button on the next line to prevent corrupting sticky menu

modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
http://screencast/cast/NjI0ODE2MjkyNTc0MDAzMnw4MDcyMmVmNy02YQ
=> Remove Copy of profile on discard click

modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.scss
Ticket: 395677144
fix: change style to prevent hide content under sticky menu
https://screenshot.googleplex.com/4yyJCHjS4kmPvgC
https://screenshot.googleplex.com/6E8Q9fVwh5gLYV3
=> 395677144: (fix) change style to prevent hide content under sticky menu

modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.ts
http://screencast/cast/NjQ3ODk0MzQ2MzkzMTkwNHw0MmQ1NGI4My00Mw
=> Clear form when Create new profile click and then Discard changes click

modules/ui/src/app/components/device-item/device-item.component.scss
=> Fix styles for tile

modules/ui/src/app/pages/testrun/testrun.component.scss, modules/ui/src/styles.scss
[Video after changes](https://screencast.googleplex.com/cast/NjU1NjgzMjQyNzQwOTQwOHwyOWE4YTY5My00YQ)
=> Fix empty state for testing page

modules/ui/src/app/pages/testrun/testrun.component.html
Ticket: 398167706
fix: [GM3] [Testing] change text mistake in the empty state
https://screenshot.googleplex.com/AujmTQFbfet9NjD
=> 398167706: (fix) [GM3] [Testing] change text mistake in the empty state

resources/test_packs/pilot/test_pack.py, resources/test_packs/qualification/test_pack.py
Incorrect steps to resolve display fixed. Empty steps to resolve page removed when steps to resolve are empty.
=> [Bug] Pilot pdf report fix

modules/ui/src/app/pages/testrun/testrun.component.scss
Ticket: 400924741
fix: [GM3] [Testing] change security tag design
https://screenshot.googleplex.com/Btbn5SbB2FMHwyZ
=> 400924741: (fix) [GM3] [Testing] change security tag design

modules/ui/src/app/app-routing.module.ts
Ticket: 406180159
fix: [a11y] change page title for testing page
https://screenshot.googleplex.com/79KoP3mQqGGFNtc
=> 406180159: (fix) [a11y] change page title for testing page

modules/ui/src/app/pages/general-settings/general-settings.component.ts
Mask form pristine after settings saved
http://screencast/cast/NDg1NzY1OTk0ODc5Mzg1Nnw2YTUyNWM4Zi00Nw
=> The Save button on settings page is not disabled after the updated settings are saved

modules/test/services/python/src/services_module.py
=> Fix KeyError 'service' in services test module

modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.scss
=> The color contrast issue on the Welcome modal

modules/ui/src/app/app.component.ts, modules/ui/src/app/app.store.spec.ts, modules/ui/src/app/app.store.ts
Focus first element in page content after callouts after redirect
http://screencast/cast/NTU0NDc1Njc0OTc5NTMyOHw3ZTAzYTdmOC04NA
=> The focus is not moved from the callout to the opened content 

modules/ui/src/app/pages/general-settings/general-settings.component.ts
Focus tab when general settings are saved
=> The focus is not visible after Save button was clicked on the Settings page

modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.html, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
Disable copy of copy
http://screencast/cast/NjYxNjExOTE2MTkxMzM0NHwwZmI4YjIzOS1iNQ
=> Restrictions for multi-clicking Copy button

modules/ui/src/app/app.component.html, modules/ui/src/app/app.component.ts
Ticket: 407724424
fix: changes for risk profile message to be displayed on all pages
=> 407724424: (fix) changes for risk profile message to be displayed on all pages

modules/ui/src/app/components/dynamic-form/dynamic-form.component.scss, modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.scss
Ticket: 406699210
fix: change styles for risk assessment form
https://screenshot.googleplex.com/4qS4YU62YDxJXtB
https://screenshot.googleplex.com/5K2MVhNjMb3V5hp
=> 406699210: (fix) change styles for risk assessment form

modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.html, modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.scss, modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.spec.ts, modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.ts
=> Test result and pilot recommendation

modules/ui/src/app/pages/risk-assessment/risk-assessment.component.html, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts
http://screencast/cast/NDYxNzgwNDgyODM3NzA4OHw5MzI2NGZkYS1jNQ
=> Fix deleting of profile

modules/ui/src/app/app.component.html, modules/ui/src/app/app.component.ts
Ticket: 407943943
fix: open profile form when redirect from profile help tip
https://screencast.googleplex.com/cast/NTI5MDYyNTA3ODM5NDg4MHwyY2JkZmRkYS0xOA
=> 407943943: (fix) open profile form when redirect from profile help tip

modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.scss
Ticket: 408378150
fix: changes for broken download pdf link
https://screenshot.googleplex.com/4rL7wcynwzAovEN
https://screencast.googleplex.com/cast/NTkyNDcyNDcyMTg0NDIyNHxkMjcxYTcyNC0yNw
=> 408378150: (fix) changes for broken download pdf link

modules/ui/src/app/app.component.scss, modules/ui/src/styles.scss
Hide Tip button when no tips available
http://screencast/cast/NjQ1OTU1NTUyNDM3ODYyNHxiZDZkYTg3My04YQ
=> The Help tips icon should disappear once the first user  is at the end

modules/ui/src/app/pages/testrun/components/test-result-dialog/test-result-dialog.component.html, modules/ui/src/app/pages/testrun/components/test-result-dialog/test-result-dialog.component.scss
Ticket: 406766143
feat: [Testing] show explanation for test result
https://screenshot.googleplex.com/52XkP4sC6N5beHM
=> 406766143: (feat) [Testing] show explanation for test result

modules/ui/src/app/app.component.scss
=> Fix side button display

modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.html, modules/ui/src/app/pages/devices/components/device-qualification-from/device-qualification-from.component.scss, modules/ui/src/app/pages/risk-assessment/profile-form/profile-form.component.scss, modules/ui/src/theming/mixins.scss
Change layout
http://screencast/cast/NjYxMTQwNDU2Mjg5MDc1MnwxMmRlMzYwNS04MQ
=> Focus: the focused field is hidden under the action bar

modules/ui/src/app/pages/testrun/testrun.component.ts
Ticket: 409247193
fix: [a11y] change focus when cancelling the start testrun
https://screencast.googleplex.com/cast/NTQzNTM4MzY2Mjc3MjIyNHw2ODJkN2JiNy1iZA
=> 409247193: (fix) [a11y] change focus when cancelling the start testrun

modules/ui/src/app/pages/general-settings/general-settings.component.html, modules/ui/src/app/pages/general-settings/general-settings.component.spec.ts, modules/ui/src/app/pages/general-settings/only-different-values.validator.ts
Ticket: 406210966
fix: make save button enable if any setting form field changed
https://screencast.googleplex.com/cast/NTcxODU0MTg1MTQyNjgxNnw2MWQ3M2IyMi05OA
=> 406210966: (fix) make save button enable if any setting form field changed

modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.html, modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.scss, modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.spec.ts
=> Fix style for status card, change style for Cancelling status

modules/ui/src/app/pages/testrun/testrun.component.html
Ticket: 409766744
feat: change title for testing empty state
https://screenshot.googleplex.com/59q4Hs2aXyte746
https://screenshot.googleplex.com/9KHYcRuovhDEURf
=> 409766744: (feat) change title for testing empty state

modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.html, modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.scss
=> Change layout for status card; fix progress bar

modules/ui/src/app/pages/devices/devices.store.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.store.spec.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.store.ts
Add new device as the first element; fix focus after adding the new RA profile
Before
http://screencast/cast/Njc1MTg4NTM1OTg0MTI4MHxiZThmY2VjOC0yYg
After
http://screencast/cast/NTYyODk0NjU1MTkzMDg4MHw2ZDE4ZDJmNy01Yg
http://screencast/cast/NDkyNjAwODcxNjE2NTEyMHxkYzY2YmYzOC0xMg
=> The Device is added to the bottom of the list

modules/ui/src/app/pages/general-settings/general-settings.component.html
Ticket: 410518000
fix: [Settings] change showing two ports value by default
https://screencast.googleplex.com/cast/NTE1NDU4MTkwOTYwMjMwNHwwNjM4MWU5Ny0xNw
https://screencast.googleplex.com/cast/NjY0ODI1MjYzMDgyNzAwOHxlMTczOWM4Mi02MQ
=> 410518000: (fix) [Settings] change showing two ports value by default

modules/ui/src/app/app.component.html, modules/ui/src/app/app.component.ts
Ticket: 410755779
fix: changes to move focus to the first interactive elem on opened page
https://screencast.googleplex.com/cast/NjI3NjQwMjEzNDM4NDY0MHxjY2NkMDFhNy02YQ
=> 410755779: (fix) changes to move focus to the first interactive elem on opened page

modules/ui/src/app/pages/devices/devices.component.ts
Ticket: 410765201
fix: make focus visible after the new device form was discarded
https://screencast.googleplex.com/cast/NjYzNjI4NjcxNzcyMjYyNHxiNGYwYzUxOS0zMA
https://screencast.googleplex.com/cast/NjIzNzk0MTI1MTcwMjc4NHwwYWJjMTAyOS02Yg
=> 410765201: (fix) make focus visible after the new device form was discarded

modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.spec.ts, modules/ui/src/app/components/version/consent-dialog/consent-dialog.component.ts, modules/ui/src/app/components/version/version.component.ts, modules/ui/src/app/pages/general-settings/general-settings.component.ts, modules/ui/src/app/services/local-storage.service.spec.ts, modules/ui/src/app/services/local-storage.service.ts, modules/ui/src/index.html
Save consent value
http://screencast/cast/NTMwMTAxMjM4OTY5MTM5MnxjZjQ1NDkyMC02ZA
=> Google Analytics checkbox is not saving 

modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.scss
Ticket: 409765421
feat: [Testing tab] adjust spacing between columns
https://screenshot.googleplex.com/3L5v2Bo3bataSXF
https://screenshot.googleplex.com/4PTrob3nYeJCQxS
=> 409765421: (feat) [Testing tab] adjust spacing between columns

modules/ui/src/app/pages/general-settings/general-settings.component.ts, modules/ui/src/styles.scss
Ticket: 411077761
fix: [a11Y] changes for focus on the settings page
https://screencast.googleplex.com/cast/NjU2ODQxNTA4MTc5MTQ4OHw0ZGJmOGJiNy1iZg
=> 411077761: (fix) [a11Y] changes for focus on the settings page

modules/ui/src/app/components/download-zip-modal/download-zip-modal.component.scss, modules/ui/src/app/components/no-entity-selected/no-entity-selected.component.scss, modules/ui/src/app/pages/general-settings/general-settings.component.scss, modules/ui/src/app/pages/reports/components/filter-dialog/filter-dialog.component.scss
Ticket: 411390117
fix: [a11Y] changes for zoom in issues
https://screencast.googleplex.com/cast/NDkxODc4NTgwMTcxNTcxMnxiYmQzY2MxYi05Nw
=> 411390117: (fix) [a11Y]: changes for zoom in issues

modules/ui/src/app/pages/reports/reports.component.ts
Prevent default event when open filter
Before
http://screencast/cast/NTM1MTM1OTc5NTY5MTUyMHwxMmFhNmQ4YS0wMQ
After
http://screencast/cast/NjY0OTY1OTM1NDI1MTI2NHw5NjllY2VjYy0xYQ
=> The date placeholder upon space clicking for Started field to be displayed

modules/ui/src/app/components/help-tip/help-tip.component.ts
small update to trigger actions
=> small update to trigger actions

modules/ui/src/app/components/device-tests/device-tests.component.scss
Ticket: 412959654
fix: make test modules visible on zoom in
https://screencast.googleplex.com/cast/NTY3ODI1MTgzNjk2NDg2NHwwODk1NTljZi05Yw
=> 412959654: (fix) make test modules visible on zoom in

modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.spec.ts, modules/ui/src/app/pages/reports/components/delete-report/delete-report.component.ts
Ticket: 412968690
fix: change delete report popup to be the same as other delete popups
https://screenshot.googleplex.com/UdqpKxLYaZeGG47
https://screenshot.googleplex.com/AFoQAPujDb3fRj6
=> 412968690: (fix) change delete report popup to be the same as other delete popups

modules/ui/src/app/pages/testrun/components/testrun-status-card/testrun-status-card.component.html
=> Show loader for stopping status

modules/ui/src/app/pages/general-settings/general-settings.store.ts
http://screencast/cast/NDc1OTQ1NzEzMjE4MzU1Mnw1NmRiN2QxYy1mMA
=> Fix settings update

resources/test_packs/pilot/report_templates/results.jinja, resources/test_packs/qualification/report_templates/results.jinja
Highlight Required if possible and Required with Non-Compliant result
=> The Non-Compliant test result is not highlighted in red in the PDF  report

modules/ui/src/app/pages/general-settings/general-settings.component.html, modules/ui/src/app/pages/general-settings/general-settings.component.scss
Ticket: 418729718
fix: change error message view for the same port selected
https://screenshot.googleplex.com/4d739wb44gyVsrL
=> 418729718: (fix) change error message view for the same port selected

modules/ui/src/app/model/testrun-status.ts, modules/ui/src/app/pages/testrun/components/test-result-dialog/test-result-dialog.component.html, modules/ui/src/app/pages/testrun/components/test-result-dialog/test-result-dialog.component.scss, modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.html, modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.scss
Ticket: 416241072
feat: provide further context in test results
https://screenshot.googleplex.com/3dgPMAemXot2YKJ
https://screenshot.googleplex.com/4MvnFmM8yQq9rb4
=> 416241072: (feat) provide further context in test results

modules/ui/src/app/pages/risk-assessment/risk-assessment.component.spec.ts, modules/ui/src/app/pages/risk-assessment/risk-assessment.component.ts, modules/ui/src/styles.scss
Ticket: 421374390
fix: change save risk profile popup design
https://screenshot.googleplex.com/5TJD4DqC8tDX5Gx
https://screenshot.googleplex.com/9aqtca2jcURqTQF
=> 421374390: (fix) change save risk profile popup design

modules/ui/src/app/pages/risk-assessment/profile-form/profile.validators.ts
As create date does not contain time, the validator function changed to compare profile
Video before changes
http://screencast/cast/NTQ4ODMxNzc5MjUxODE0NHwwYTI4MWIzOS02Yg
After
http://screencast/cast/NTY5MzI0MTAwNDM5MjQ0OHwwNWM5N2IwNS00Mw
=> The risk profile duplicate can be created 

modules/ui/src/app/model/device.ts, modules/ui/src/app/services/test-run.service.ts
=> FE: Refactor RA date format - add time

framework/python/src/common/testreport.py, resources/report/test_report_styles.css, resources/test_packs/pilot/report_templates/report_template.html, resources/test_packs/pilot/report_templates/results.jinja, resources/test_packs/qualification/report_templates/report_template.html, resources/test_packs/qualification/report_templates/results.jinja
[report (34).zip](https://github.com/user-attachments/files/21015662/report.34.zip)
@sofyakurilova  Please, check styles.
=> Test result details

modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.html, modules/ui/src/app/pages/testrun/components/testrun-table/testrun-table.component.scss
Fix css
Screenshot after changes https://screenshot.googleplex.com/3qmp25DKUHCo3y5
=> [TR] The font for test description on the testing page is not by design 

framework/python/src/common/testreport.py, resources/report/test_report_styles.css, resources/test_packs/pilot/report_templates/results.jinja, resources/test_packs/qualification/report_templates/results.jinja
report examples
[report_pilot.pdf](https://github.com/user-attachments/files/21547126/report_pilot.pdf)
[report_qualification.pdf](https://github.com/user-attachments/files/21547128/report_qualification.pdf)
=> Report description field line break
